#!/bin/bash
xpub add discourse about-maas.md "About MAAS (snap/2.7/CLI)" 5
xpub add discourse about-maas.md "About MAAS (snap/2.7/UI)" 5
xpub add discourse about-maas.md "About MAAS (snap/2.8/CLI)" 5
xpub add discourse about-maas.md "About MAAS (snap/2.8/UI)" 5
xpub add discourse about-maas.md "About MAAS (snap/2.9/CLI)" 5
xpub add discourse about-maas.md "About MAAS (snap/2.9/UI)" 5
xpub add discourse about-maas.md "About MAAS (deb/2.7/CLI)" 5
xpub add discourse about-maas.md "About MAAS (deb/2.7/UI)" 5
xpub add discourse about-maas.md "About MAAS (deb/2.8/CLI)" 5
xpub add discourse about-maas.md "About MAAS (deb/2.8/UI)" 5
xpub add discourse about-maas.md "About MAAS (deb/2.9/CLI)" 5
xpub add discourse about-maas.md "About MAAS (deb/2.9/UI)" 5
xpub add discourse add-machines.md "Add machines (snap/2.7/CLI)" 5
xpub add discourse add-machines.md "Add machines (snap/2.7/UI)" 5
xpub add discourse add-machines.md "Add machines (snap/2.8/CLI)" 5
xpub add discourse add-machines.md "Add machines (snap/2.8/UI)" 5
xpub add discourse add-machines.md "Add machines (snap/2.9/CLI)" 5
xpub add discourse add-machines.md "Add machines (snap/2.9/UI)" 5
xpub add discourse add-machines.md "Add machines (deb/2.7/CLI)" 5
xpub add discourse add-machines.md "Add machines (deb/2.7/UI)" 5
xpub add discourse add-machines.md "Add machines (deb/2.8/CLI)" 5
xpub add discourse add-machines.md "Add machines (deb/2.8/UI)" 5
xpub add discourse add-machines.md "Add machines (deb/2.9/CLI)" 5
xpub add discourse add-machines.md "Add machines (deb/2.9/UI)" 5
xpub add discourse adding-a-vm-host.md "Adding a VM host (snap/2.7/CLI)" 5
xpub add discourse adding-a-vm-host.md "Adding a VM host (snap/2.7/UI)" 5
xpub add discourse adding-a-vm-host.md "Adding a VM host (snap/2.8/CLI)" 5
xpub add discourse adding-a-vm-host.md "Adding a VM host (snap/2.8/UI)" 5
xpub add discourse adding-a-vm-host.md "Adding a VM host (snap/2.9/CLI)" 5
xpub add discourse adding-a-vm-host.md "Adding a VM host (snap/2.9/UI)" 5
xpub add discourse adding-a-vm-host.md "Adding a VM host (deb/2.7/CLI)" 5
xpub add discourse adding-a-vm-host.md "Adding a VM host (deb/2.7/UI)" 5
xpub add discourse adding-a-vm-host.md "Adding a VM host (deb/2.8/CLI)" 5
xpub add discourse adding-a-vm-host.md "Adding a VM host (deb/2.8/UI)" 5
xpub add discourse adding-a-vm-host.md "Adding a VM host (deb/2.9/CLI)" 5
xpub add discourse adding-a-vm-host.md "Adding a VM host (deb/2.9/UI)" 5
xpub add discourse api-authentication.md "API authentication (snap/2.7/CLI)" 5
xpub add discourse api-authentication.md "API authentication (snap/2.7/UI)" 5
xpub add discourse api-authentication.md "API authentication (snap/2.8/CLI)" 5
xpub add discourse api-authentication.md "API authentication (snap/2.8/UI)" 5
xpub add discourse api-authentication.md "API authentication (snap/2.9/CLI)" 5
xpub add discourse api-authentication.md "API authentication (snap/2.9/UI)" 5
xpub add discourse api-authentication.md "API authentication (deb/2.7/CLI)" 5
xpub add discourse api-authentication.md "API authentication (deb/2.7/UI)" 5
xpub add discourse api-authentication.md "API authentication (deb/2.8/CLI)" 5
xpub add discourse api-authentication.md "API authentication (deb/2.8/UI)" 5
xpub add discourse api-authentication.md "API authentication (deb/2.9/CLI)" 5
xpub add discourse api-authentication.md "API authentication (deb/2.9/UI)" 5
xpub add discourse audit-event-logs.md "Audit event logs (snap/2.7/CLI)" 5
xpub add discourse audit-event-logs.md "Audit event logs (snap/2.7/UI)" 5
xpub add discourse audit-event-logs.md "Audit event logs (snap/2.8/CLI)" 5
xpub add discourse audit-event-logs.md "Audit event logs (snap/2.8/UI)" 5
xpub add discourse audit-event-logs.md "Audit event logs (snap/2.9/CLI)" 5
xpub add discourse audit-event-logs.md "Audit event logs (snap/2.9/UI)" 5
xpub add discourse audit-event-logs.md "Audit event logs (deb/2.7/CLI)" 5
xpub add discourse audit-event-logs.md "Audit event logs (deb/2.7/UI)" 5
xpub add discourse audit-event-logs.md "Audit event logs (deb/2.8/CLI)" 5
xpub add discourse audit-event-logs.md "Audit event logs (deb/2.8/UI)" 5
xpub add discourse audit-event-logs.md "Audit event logs (deb/2.9/CLI)" 5
xpub add discourse audit-event-logs.md "Audit event logs (deb/2.9/UI)" 5
xpub add discourse availability-zones.md "Availability zones (snap/2.7/CLI)" 5
xpub add discourse availability-zones.md "Availability zones (snap/2.7/UI)" 5
xpub add discourse availability-zones.md "Availability zones (snap/2.8/CLI)" 5
xpub add discourse availability-zones.md "Availability zones (snap/2.8/UI)" 5
xpub add discourse availability-zones.md "Availability zones (snap/2.9/CLI)" 5
xpub add discourse availability-zones.md "Availability zones (snap/2.9/UI)" 5
xpub add discourse availability-zones.md "Availability zones (deb/2.7/CLI)" 5
xpub add discourse availability-zones.md "Availability zones (deb/2.7/UI)" 5
xpub add discourse availability-zones.md "Availability zones (deb/2.8/CLI)" 5
xpub add discourse availability-zones.md "Availability zones (deb/2.8/UI)" 5
xpub add discourse availability-zones.md "Availability zones (deb/2.9/CLI)" 5
xpub add discourse availability-zones.md "Availability zones (deb/2.9/UI)" 5
xpub add discourse backup.md "Backup (snap/2.7/CLI)" 5
xpub add discourse backup.md "Backup (snap/2.7/UI)" 5
xpub add discourse backup.md "Backup (snap/2.8/CLI)" 5
xpub add discourse backup.md "Backup (snap/2.8/UI)" 5
xpub add discourse backup.md "Backup (snap/2.9/CLI)" 5
xpub add discourse backup.md "Backup (snap/2.9/UI)" 5
xpub add discourse backup.md "Backup (deb/2.7/CLI)" 5
xpub add discourse backup.md "Backup (deb/2.7/UI)" 5
xpub add discourse backup.md "Backup (deb/2.8/CLI)" 5
xpub add discourse backup.md "Backup (deb/2.8/UI)" 5
xpub add discourse backup.md "Backup (deb/2.9/CLI)" 5
xpub add discourse backup.md "Backup (deb/2.9/UI)" 5
xpub add discourse block-devices.md "Block devices (snap/2.7/CLI)" 5
xpub add discourse block-devices.md "Block devices (snap/2.7/UI)" 5
xpub add discourse block-devices.md "Block devices (snap/2.8/CLI)" 5
xpub add discourse block-devices.md "Block devices (snap/2.8/UI)" 5
xpub add discourse block-devices.md "Block devices (snap/2.9/CLI)" 5
xpub add discourse block-devices.md "Block devices (snap/2.9/UI)" 5
xpub add discourse block-devices.md "Block devices (deb/2.7/CLI)" 5
xpub add discourse block-devices.md "Block devices (deb/2.7/UI)" 5
xpub add discourse block-devices.md "Block devices (deb/2.8/CLI)" 5
xpub add discourse block-devices.md "Block devices (deb/2.8/UI)" 5
xpub add discourse block-devices.md "Block devices (deb/2.9/CLI)" 5
xpub add discourse block-devices.md "Block devices (deb/2.9/UI)" 5
xpub add discourse cli-advanced-tasks.md "CLI advanced tasks (snap/2.7/CLI)" 5
xpub add discourse cli-advanced-tasks.md "CLI advanced tasks (snap/2.7/UI)" 5
xpub add discourse cli-advanced-tasks.md "CLI advanced tasks (snap/2.8/CLI)" 5
xpub add discourse cli-advanced-tasks.md "CLI advanced tasks (snap/2.8/UI)" 5
xpub add discourse cli-advanced-tasks.md "CLI advanced tasks (snap/2.9/CLI)" 5
xpub add discourse cli-advanced-tasks.md "CLI advanced tasks (snap/2.9/UI)" 5
xpub add discourse cli-advanced-tasks.md "CLI advanced tasks (deb/2.7/CLI)" 5
xpub add discourse cli-advanced-tasks.md "CLI advanced tasks (deb/2.7/UI)" 5
xpub add discourse cli-advanced-tasks.md "CLI advanced tasks (deb/2.8/CLI)" 5
xpub add discourse cli-advanced-tasks.md "CLI advanced tasks (deb/2.8/UI)" 5
xpub add discourse cli-advanced-tasks.md "CLI advanced tasks (deb/2.9/CLI)" 5
xpub add discourse cli-advanced-tasks.md "CLI advanced tasks (deb/2.9/UI)" 5
xpub add discourse cli-commissioning-and-hardware-testing-scripts.md "CLI commissioning and hardware testing scripts (snap/2.7/CLI)" 5
xpub add discourse cli-commissioning-and-hardware-testing-scripts.md "CLI commissioning and hardware testing scripts (snap/2.7/UI)" 5
xpub add discourse cli-commissioning-and-hardware-testing-scripts.md "CLI commissioning and hardware testing scripts (snap/2.8/CLI)" 5
xpub add discourse cli-commissioning-and-hardware-testing-scripts.md "CLI commissioning and hardware testing scripts (snap/2.8/UI)" 5
xpub add discourse cli-commissioning-and-hardware-testing-scripts.md "CLI commissioning and hardware testing scripts (snap/2.9/CLI)" 5
xpub add discourse cli-commissioning-and-hardware-testing-scripts.md "CLI commissioning and hardware testing scripts (snap/2.9/UI)" 5
xpub add discourse cli-commissioning-and-hardware-testing-scripts.md "CLI commissioning and hardware testing scripts (deb/2.7/CLI)" 5
xpub add discourse cli-commissioning-and-hardware-testing-scripts.md "CLI commissioning and hardware testing scripts (deb/2.7/UI)" 5
xpub add discourse cli-commissioning-and-hardware-testing-scripts.md "CLI commissioning and hardware testing scripts (deb/2.8/CLI)" 5
xpub add discourse cli-commissioning-and-hardware-testing-scripts.md "CLI commissioning and hardware testing scripts (deb/2.8/UI)" 5
xpub add discourse cli-commissioning-and-hardware-testing-scripts.md "CLI commissioning and hardware testing scripts (deb/2.9/CLI)" 5
xpub add discourse cli-commissioning-and-hardware-testing-scripts.md "CLI commissioning and hardware testing scripts (deb/2.9/UI)" 5
xpub add discourse cli-composable-hardware.md "CLI composable hardware (snap/2.7/CLI)" 5
xpub add discourse cli-composable-hardware.md "CLI composable hardware (snap/2.7/UI)" 5
xpub add discourse cli-composable-hardware.md "CLI composable hardware (snap/2.8/CLI)" 5
xpub add discourse cli-composable-hardware.md "CLI composable hardware (snap/2.8/UI)" 5
xpub add discourse cli-composable-hardware.md "CLI composable hardware (snap/2.9/CLI)" 5
xpub add discourse cli-composable-hardware.md "CLI composable hardware (snap/2.9/UI)" 5
xpub add discourse cli-composable-hardware.md "CLI composable hardware (deb/2.7/CLI)" 5
xpub add discourse cli-composable-hardware.md "CLI composable hardware (deb/2.7/UI)" 5
xpub add discourse cli-composable-hardware.md "CLI composable hardware (deb/2.8/CLI)" 5
xpub add discourse cli-composable-hardware.md "CLI composable hardware (deb/2.8/UI)" 5
xpub add discourse cli-composable-hardware.md "CLI composable hardware (deb/2.9/CLI)" 5
xpub add discourse cli-composable-hardware.md "CLI composable hardware (deb/2.9/UI)" 5
xpub add discourse cli-dhcp-snippet-management.md "CLI DHCP snippet management (snap/2.7/CLI)" 5
xpub add discourse cli-dhcp-snippet-management.md "CLI DHCP snippet management (snap/2.7/UI)" 5
xpub add discourse cli-dhcp-snippet-management.md "CLI DHCP snippet management (snap/2.8/CLI)" 5
xpub add discourse cli-dhcp-snippet-management.md "CLI DHCP snippet management (snap/2.8/UI)" 5
xpub add discourse cli-dhcp-snippet-management.md "CLI DHCP snippet management (snap/2.9/CLI)" 5
xpub add discourse cli-dhcp-snippet-management.md "CLI DHCP snippet management (snap/2.9/UI)" 5
xpub add discourse cli-dhcp-snippet-management.md "CLI DHCP snippet management (deb/2.7/CLI)" 5
xpub add discourse cli-dhcp-snippet-management.md "CLI DHCP snippet management (deb/2.7/UI)" 5
xpub add discourse cli-dhcp-snippet-management.md "CLI DHCP snippet management (deb/2.8/CLI)" 5
xpub add discourse cli-dhcp-snippet-management.md "CLI DHCP snippet management (deb/2.8/UI)" 5
xpub add discourse cli-dhcp-snippet-management.md "CLI DHCP snippet management(deb/2.9/CLI)" 5
xpub add discourse cli-dhcp-snippet-management.md "CLI DHCP snippet management (deb/2.9/UI)" 5
xpub add discourse cli-image-management.md "CLI image management (snap/2.7/CLI)" 5
xpub add discourse cli-image-management.md "CLI image management (snap/2.7/UI)" 5
xpub add discourse cli-image-management.md "CLI image management (snap/2.8/CLI)" 5
xpub add discourse cli-image-management.md "CLI image management (snap/2.8/UI)" 5
xpub add discourse cli-image-management.md "CLI image management (snap/2.9/CLI)" 5
xpub add discourse cli-image-management.md "CLI image management (snap/2.9/UI)" 5
xpub add discourse cli-image-management.md "CLI image management (deb/2.7/CLI)" 5
xpub add discourse cli-image-management.md "CLI image management (deb/2.7/UI)" 5
xpub add discourse cli-image-management.md "CLI image management (deb/2.8/CLI)" 5
xpub add discourse cli-image-management.md "CLI image management (deb/2.8/UI)" 5
xpub add discourse cli-image-management.md "CLI image management (deb/2.9/CLI)" 5
xpub add discourse cli-image-management.md "CLI image management (deb/2.9/UI)" 5
xpub add discourse cli-interface-management.md "CLI interface management (snap/2.7/CLI)" 5
xpub add discourse cli-interface-management.md "CLI interface management (snap/2.7/UI)" 5
xpub add discourse cli-interface-management.md "CLI interface management (snap/2.8/CLI)" 5
xpub add discourse cli-interface-management.md "CLI interface management (snap/2.8/UI)" 5
xpub add discourse cli-interface-management.md "CLI interface management (snap/2.9/CLI)" 5
xpub add discourse cli-interface-management.md "CLI interface management (snap/2.9/UI)" 5
xpub add discourse cli-interface-management.md "CLI interface management (deb/2.7/CLI)" 5
xpub add discourse cli-interface-management.md "CLI interface management (deb/2.7/UI)" 5
xpub add discourse cli-interface-management.md "CLI interface management (deb/2.8/CLI)" 5
xpub add discourse cli-interface-management.md "CLI interface management (deb/2.8/UI)" 5
xpub add discourse cli-interface-management.md "CLI interface management (deb/2.9/CLI)" 5
xpub add discourse cli-interface-management.md "CLI interface management (deb/2.9/UI)" 5
xpub add discourse cli-kernel-management.md "CLI kernel management (snap/2.7/CLI)" 5
xpub add discourse cli-kernel-management.md "CLI kernel management (snap/2.7/UI)" 5
xpub add discourse cli-kernel-management.md "CLI kernel management (snap/2.8/CLI)" 5
xpub add discourse cli-kernel-management.md "CLI kernel management (snap/2.8/UI)" 5
xpub add discourse cli-kernel-management.md "CLI kernel management (snap/2.9/CLI)" 5
xpub add discourse cli-kernel-management.md "CLI kernel management (snap/2.9/UI)" 5
xpub add discourse cli-kernel-management.md "CLI kernel management (deb/2.7/CLI)" 5
xpub add discourse cli-kernel-management.md "CLI kernel management (deb/2.7/UI)" 5
xpub add discourse cli-kernel-management.md "CLI kernel management (deb/2.8/CLI)" 5
xpub add discourse cli-kernel-management.md "CLI kernel management (deb/2.8/UI)" 5
xpub add discourse cli-kernel-management.md "CLI kernel management (deb/2.9/CLI)" 5
xpub add discourse cli-kernel-management.md "CLI kernel management (deb/2.9/UI)" 5
xpub add discourse cli-resource-pool-management.md "CLI resource pool management (snap/2.7/CLI)" 5
xpub add discourse cli-resource-pool-management.md "CLI resource pool management (snap/2.7/UI)" 5
xpub add discourse cli-resource-pool-management.md "CLI resource pool management (snap/2.8/CLI)" 5
xpub add discourse cli-resource-pool-management.md "CLI resource pool management (snap/2.8/UI)" 5
xpub add discourse cli-resource-pool-management.md "CLI resource pool management (snap/2.9/CLI)" 5
xpub add discourse cli-resource-pool-management.md "CLI resource pool management (snap/2.9/UI)" 5
xpub add discourse cli-resource-pool-management.md "CLI resource pool management (deb/2.7/CLI)" 5
xpub add discourse cli-resource-pool-management.md "CLI resource pool management (deb/2.7/UI)" 5
xpub add discourse cli-resource-pool-management.md "CLI resource pool management (deb/2.8/CLI)" 5
xpub add discourse cli-resource-pool-management.md "CLI resource pool management (deb/2.8/UI)" 5
xpub add discourse cli-resource-pool-management.md "CLI resource pool management (deb/2.9/CLI)" 5
xpub add discourse cli-resource-pool-management.md "CLI resource pool management (deb/2.9/UI)" 5
xpub add discourse cli-tag-management.md "CLI tag management (snap/2.7/CLI)" 5
xpub add discourse cli-tag-management.md "CLI tag management (snap/2.7/UI)" 5
xpub add discourse cli-tag-management.md "CLI tag management (snap/2.8/CLI)" 5
xpub add discourse cli-tag-management.md "CLI tag management (snap/2.8/UI)" 5
xpub add discourse cli-tag-management.md "CLI tag management (snap/2.9/CLI)" 5
xpub add discourse cli-tag-management.md "CLI tag management (snap/2.9/UI)" 5
xpub add discourse cli-tag-management.md "CLI tag management (deb/2.7/CLI)" 5
xpub add discourse cli-tag-management.md "CLI tag management (deb/2.7/UI)" 5
xpub add discourse cli-tag-management.md "CLI tag management (deb/2.8/CLI)" 5
xpub add discourse cli-tag-management.md "CLI tag management (deb/2.8/UI)" 5
xpub add discourse cli-tag-management.md "CLI tag management (deb/2.9/CLI)" 5
xpub add discourse cli-tag-management.md "CLI tag management (deb/2.9/UI)" 5
xpub add discourse commission-machines.md "Commission machines (snap/2.7/CLI)" 5
xpub add discourse commission-machines.md "Commission machines (snap/2.7/UI)" 5
xpub add discourse commission-machines.md "Commission machines (snap/2.8/CLI)" 5
xpub add discourse commission-machines.md "Commission machines (snap/2.8/UI)" 5
xpub add discourse commission-machines.md "Commission machines (snap/2.9/CLI)" 5
xpub add discourse commission-machines.md "Commission machines (snap/2.9/UI)" 5
xpub add discourse commission-machines.md "Commission machines (deb/2.7/CLI)" 5
xpub add discourse commission-machines.md "Commission machines (deb/2.7/UI)" 5
xpub add discourse commission-machines.md "Commission machines (deb/2.8/CLI)" 5
xpub add discourse commission-machines.md "Commission machines (deb/2.8/UI)" 5
xpub add discourse commission-machines.md "Commission machines (deb/2.9/CLI)" 5
xpub add discourse commission-machines.md "Commission machines (deb/2.9/UI)" 5
xpub add discourse commissioning-and-hardware-testing-scripts.md "Commissioning and hardware testing scripts (snap/2.7/CLI)" 5
xpub add discourse commissioning-and-hardware-testing-scripts.md "Commissioning and hardware testing scripts (snap/2.7/UI)" 5
xpub add discourse commissioning-and-hardware-testing-scripts.md "Commissioning and hardware testing scripts (snap/2.8/CLI)" 5
xpub add discourse commissioning-and-hardware-testing-scripts.md "Commissioning and hardware testing scripts (snap/2.8/UI)" 5
xpub add discourse commissioning-and-hardware-testing-scripts.md "Commissioning and hardware testing scripts (snap/2.9/CLI)" 5
xpub add discourse commissioning-and-hardware-testing-scripts.md "Commissioning and hardware testing scripts (snap/2.9/UI)" 5
xpub add discourse commissioning-and-hardware-testing-scripts.md "Commissioning and hardware testing scripts (deb/2.7/CLI)" 5
xpub add discourse commissioning-and-hardware-testing-scripts.md "Commissioning and hardware testing scripts (deb/2.7/UI)" 5
xpub add discourse commissioning-and-hardware-testing-scripts.md "Commissioning and hardware testing scripts (deb/2.8/CLI)" 5
xpub add discourse commissioning-and-hardware-testing-scripts.md "Commissioning and hardware testing scripts (deb/2.8/UI)" 5
xpub add discourse commissioning-and-hardware-testing-scripts.md "Commissioning and hardware testing scripts(deb/2.9/CLI)" 5
xpub add discourse commissioning-and-hardware-testing-scripts.md "Commissioning and hardware testing scripts (deb/2.9/UI)" 5
xpub add discourse commissioning-logs.md "Commissioning logs (snap/2.7/CLI)" 5
xpub add discourse commissioning-logs.md "Commissioning logs (snap/2.7/UI)" 5
xpub add discourse commissioning-logs.md "Commissioning logs (snap/2.8/CLI)" 5
xpub add discourse commissioning-logs.md "Commissioning logs (snap/2.8/UI)" 5
xpub add discourse commissioning-logs.md "Commissioning logs (snap/2.9/CLI)" 5
xpub add discourse commissioning-logs.md "Commissioning logs (snap/2.9/UI)" 5
xpub add discourse commissioning-logs.md "Commissioning logs (deb/2.7/CLI)" 5
xpub add discourse commissioning-logs.md "Commissioning logs (deb/2.7/UI)" 5
xpub add discourse commissioning-logs.md "Commissioning logs (deb/2.8/CLI)" 5
xpub add discourse commissioning-logs.md "Commissioning logs (deb/2.8/UI)" 5
xpub add discourse commissioning-logs.md "Commissioning logs (deb/2.9/CLI)" 5
xpub add discourse commissioning-logs.md "Commissioning logs (deb/2.9/UI)" 5
xpub add discourse common-cli-tasks.md "Common CLI tasks (snap/2.7/CLI)" 5
xpub add discourse common-cli-tasks.md "Common CLI tasks (snap/2.7/UI)" 5
xpub add discourse common-cli-tasks.md "Common CLI tasks (snap/2.8/CLI)" 5
xpub add discourse common-cli-tasks.md "Common CLI tasks (snap/2.8/UI)" 5
xpub add discourse common-cli-tasks.md "Common CLI tasks (snap/2.9/CLI)" 5
xpub add discourse common-cli-tasks.md "Common CLI tasks (snap/2.9/UI)" 5
xpub add discourse common-cli-tasks.md "Common CLI tasks (deb/2.7/CLI)" 5
xpub add discourse common-cli-tasks.md "Common CLI tasks (deb/2.7/UI)" 5
xpub add discourse common-cli-tasks.md "Common CLI tasks (deb/2.8/CLI)" 5
xpub add discourse common-cli-tasks.md "Common CLI tasks (deb/2.8/UI)" 5
xpub add discourse common-cli-tasks.md "Common CLI tasks (deb/2.9/CLI)" 5
xpub add discourse common-cli-tasks.md "Common CLI tasks (deb/2.9/UI)" 5
xpub add discourse concepts-and-terms.md "Concepts and terms (snap/2.7/CLI)" 5
xpub add discourse concepts-and-terms.md "Concepts and terms (snap/2.7/UI)" 5
xpub add discourse concepts-and-terms.md "Concepts and terms (snap/2.8/CLI)" 5
xpub add discourse concepts-and-terms.md "Concepts and terms (snap/2.8/UI)" 5
xpub add discourse concepts-and-terms.md "Concepts and terms (snap/2.9/CLI)" 5
xpub add discourse concepts-and-terms.md "Concepts and terms (snap/2.9/UI)" 5
xpub add discourse concepts-and-terms.md "Concepts and terms (deb/2.7/CLI)" 5
xpub add discourse concepts-and-terms.md "Concepts and terms (deb/2.7/UI)" 5
xpub add discourse concepts-and-terms.md "Concepts and terms (deb/2.8/CLI)" 5
xpub add discourse concepts-and-terms.md "Concepts and terms (deb/2.8/UI)" 5
xpub add discourse concepts-and-terms.md "Concepts and terms (deb/2.9/CLI)" 5
xpub add discourse concepts-and-terms.md "Concepts and terms (deb/2.9/UI)" 5
xpub add discourse configuration-journey.md "Configuration journey (snap/2.7/CLI)" 5
xpub add discourse configuration-journey.md "Configuration journey (snap/2.7/UI)" 5
xpub add discourse configuration-journey.md "Configuration journey (snap/2.8/CLI)" 5
xpub add discourse configuration-journey.md "Configuration journey (snap/2.8/UI)" 5
xpub add discourse configuration-journey.md "Configuration journey (snap/2.9/CLI)" 5
xpub add discourse configuration-journey.md "Configuration journey (snap/2.9/UI)" 5
xpub add discourse configuration-journey.md "Configuration journey (deb/2.7/CLI)" 5
xpub add discourse configuration-journey.md "Configuration journey (deb/2.7/UI)" 5
xpub add discourse configuration-journey.md "Configuration journey (deb/2.8/CLI)" 5
xpub add discourse configuration-journey.md "Configuration journey (deb/2.8/UI)" 5
xpub add discourse configuration-journey.md "Configuration journey (deb/2.9/CLI)" 5
xpub add discourse configuration-journey.md "Configuration journey (deb/2.9/UI)" 5
xpub add discourse configuring-tls-encryption.md "Configuring TLS encryption (snap/2.7/CLI)" 5
xpub add discourse configuring-tls-encryption.md "Configuring TLS encryption (snap/2.7/UI)" 5
xpub add discourse configuring-tls-encryption.md "Configuring TLS encryption (snap/2.8/CLI)" 5
xpub add discourse configuring-tls-encryption.md "Configuring TLS encryption (snap/2.8/UI)" 5
xpub add discourse configuring-tls-encryption.md "Configuring TLS encryption (snap/2.9/CLI)" 5
xpub add discourse configuring-tls-encryption.md "Configuring TLS encryption (snap/2.9/UI)" 5
xpub add discourse configuring-tls-encryption.md "Configuring TLS encryption (deb/2.7/CLI)" 5
xpub add discourse configuring-tls-encryption.md "Configuring TLS encryption (deb/2.7/UI)" 5
xpub add discourse configuring-tls-encryption.md "Configuring TLS encryption (deb/2.8/CLI)" 5
xpub add discourse configuring-tls-encryption.md "Configuring TLS encryption (deb/2.8/UI)" 5
xpub add discourse configuring-tls-encryption.md "Configuring TLS encryption (deb/2.9/CLI)" 5
xpub add discourse configuring-tls-encryption.md "Configuring TLS encryption (deb/2.9/UI)" 5
xpub add discourse contact-us.md "Contact us (snap/2.7/CLI)" 5
xpub add discourse contact-us.md "Contact us (snap/2.7/UI)" 5
xpub add discourse contact-us.md "Contact us (snap/2.8/CLI)" 5
xpub add discourse contact-us.md "Contact us (snap/2.8/UI)" 5
xpub add discourse contact-us.md "Contact us (snap/2.9/CLI)" 5
xpub add discourse contact-us.md "Contact us (snap/2.9/UI)" 5
xpub add discourse contact-us.md "Contact us (deb/2.7/CLI)" 5
xpub add discourse contact-us.md "Contact us (deb/2.7/UI)" 5
xpub add discourse contact-us.md "Contact us (deb/2.8/CLI)" 5
xpub add discourse contact-us.md "Contact us (deb/2.8/UI)" 5
xpub add discourse contact-us.md "Contact us (deb/2.9/CLI)" 5
xpub add discourse contact-us.md "Contact us (deb/2.9/UI)" 5
xpub add discourse creating-a-custom-ubuntu-image.md "Creating a custom Ubuntu image (snap/2.7/CLI)" 5
xpub add discourse creating-a-custom-ubuntu-image.md "Creating a custom Ubuntu image (snap/2.7/UI)" 5
xpub add discourse creating-a-custom-ubuntu-image.md "Creating a custom Ubuntu image (snap/2.8/CLI)" 5
xpub add discourse creating-a-custom-ubuntu-image.md "Creating a custom Ubuntu image (snap/2.8/UI)" 5
xpub add discourse creating-a-custom-ubuntu-image.md "Creating a custom Ubuntu image (snap/2.9/CLI)" 5
xpub add discourse creating-a-custom-ubuntu-image.md "Creating a custom Ubuntu image (snap/2.9/UI)" 5
xpub add discourse creating-a-custom-ubuntu-image.md "Creating a custom Ubuntu image (deb/2.7/CLI)" 5
xpub add discourse creating-a-custom-ubuntu-image.md "Creating a custom Ubuntu image (deb/2.7/UI)" 5
xpub add discourse creating-a-custom-ubuntu-image.md "Creating a custom Ubuntu image (deb/2.8/CLI)" 5
xpub add discourse creating-a-custom-ubuntu-image.md "Creating a custom Ubuntu image (deb/2.8/UI)" 5
xpub add discourse creating-a-custom-ubuntu-image.md "Creating a custom Ubuntu image (deb/2.9/CLI)" 5
xpub add discourse creating-a-custom-ubuntu-image.md "Creating a custom Ubuntu image (deb/2.9/UI)" 5
xpub add discourse creating-and-deleting-vms.md "Creating and deleting VMs (snap/2.7/CLI)" 5
xpub add discourse creating-and-deleting-vms.md "Creating and deleting VMs (snap/2.7/UI)" 5
xpub add discourse creating-and-deleting-vms.md "Creating and deleting VMs (snap/2.8/CLI)" 5
xpub add discourse creating-and-deleting-vms.md "Creating and deleting VMs (snap/2.8/UI)" 5
xpub add discourse creating-and-deleting-vms.md "Creating and deleting VMs (snap/2.9/CLI)" 5
xpub add discourse creating-and-deleting-vms.md "Creating and deleting VMs (snap/2.9/UI)" 5
xpub add discourse creating-and-deleting-vms.md "Creating and deleting VMs (deb/2.7/CLI)" 5
xpub add discourse creating-and-deleting-vms.md "Creating and deleting VMs (deb/2.7/UI)" 5
xpub add discourse creating-and-deleting-vms.md "Creating and deleting VMs (deb/2.8/CLI)" 5
xpub add discourse creating-and-deleting-vms.md "Creating and deleting VMs (deb/2.8/UI)" 5
xpub add discourse creating-and-deleting-vms.md "Creating and deleting VMs (deb/2.9/CLI)" 5
xpub add discourse creating-and-deleting-vms.md "Creating and deleting VMs (deb/2.9/UI)" 5
xpub add discourse custom-machine-setup.md "Custom machine setup (snap/2.7/CLI)" 5
xpub add discourse custom-machine-setup.md "Custom machine setup (snap/2.7/UI)" 5
xpub add discourse custom-machine-setup.md "Custom machine setup (snap/2.8/CLI)" 5
xpub add discourse custom-machine-setup.md "Custom machine setup (snap/2.8/UI)" 5
xpub add discourse custom-machine-setup.md "Custom machine setup (snap/2.9/CLI)" 5
xpub add discourse custom-machine-setup.md "Custom machine setup (snap/2.9/UI)" 5
xpub add discourse custom-machine-setup.md "Custom machine setup (deb/2.7/CLI)" 5
xpub add discourse custom-machine-setup.md "Custom machine setup (deb/2.7/UI)" 5
xpub add discourse custom-machine-setup.md "Custom machine setup (deb/2.8/CLI)" 5
xpub add discourse custom-machine-setup.md "Custom machine setup (deb/2.8/UI)" 5
xpub add discourse custom-machine-setup.md "Custom machine setup (deb/2.9/CLI)" 5
xpub add discourse custom-machine-setup.md "Custom machine setup (deb/2.9/UI)" 5
xpub add discourse deploy-machines.md "Deploy machines (snap/2.7/CLI)" 5
xpub add discourse deploy-machines.md "Deploy machines (snap/2.7/UI)" 5
xpub add discourse deploy-machines.md "Deploy machines (snap/2.8/CLI)" 5
xpub add discourse deploy-machines.md "Deploy machines (snap/2.8/UI)" 5
xpub add discourse deploy-machines.md "Deploy machines (snap/2.9/CLI)" 5
xpub add discourse deploy-machines.md "Deploy machines (snap/2.9/UI)" 5
xpub add discourse deploy-machines.md "Deploy machines (deb/2.7/CLI)" 5
xpub add discourse deploy-machines.md "Deploy machines (deb/2.7/UI)" 5
xpub add discourse deploy-machines.md "Deploy machines (deb/2.8/CLI)" 5
xpub add discourse deploy-machines.md "Deploy machines (deb/2.8/UI)" 5
xpub add discourse deploy-machines.md "Deploy machines (deb/2.9/CLI)" 5
xpub add discourse deploy-machines.md "Deploy machines (deb/2.9/UI)" 5
xpub add discourse disk-erasure.md "Disk erasure (snap/2.7/CLI)" 5
xpub add discourse disk-erasure.md "Disk erasure (snap/2.7/UI)" 5
xpub add discourse disk-erasure.md "Disk erasure (snap/2.8/CLI)" 5
xpub add discourse disk-erasure.md "Disk erasure (snap/2.8/UI)" 5
xpub add discourse disk-erasure.md "Disk erasure (snap/2.9/CLI)" 5
xpub add discourse disk-erasure.md "Disk erasure (snap/2.9/UI)" 5
xpub add discourse disk-erasure.md "Disk erasure (deb/2.7/CLI)" 5
xpub add discourse disk-erasure.md "Disk erasure (deb/2.7/UI)" 5
xpub add discourse disk-erasure.md "Disk erasure (deb/2.8/CLI)" 5
xpub add discourse disk-erasure.md "Disk erasure (deb/2.8/UI)" 5
xpub add discourse disk-erasure.md "Disk erasure (deb/2.9/CLI)" 5
xpub add discourse disk-erasure.md "Disk erasure (deb/2.9/UI)" 5
xpub add discourse enabling-maas.md "Enabling MAAS (snap/2.7/CLI)" 5
xpub add discourse enabling-maas.md "Enabling MAAS (snap/2.7/UI)" 5
xpub add discourse enabling-maas.md "Enabling MAAS (snap/2.8/CLI)" 5
xpub add discourse enabling-maas.md "Enabling MAAS (snap/2.8/UI)" 5
xpub add discourse enabling-maas.md "Enabling MAAS (snap/2.9/CLI)" 5
xpub add discourse enabling-maas.md "Enabling MAAS (snap/2.9/UI)" 5
xpub add discourse enabling-maas.md "Enabling MAAS (deb/2.7/CLI)" 5
xpub add discourse enabling-maas.md "Enabling MAAS (deb/2.7/UI)" 5
xpub add discourse enabling-maas.md "Enabling MAAS (deb/2.8/CLI)" 5
xpub add discourse enabling-maas.md "Enabling MAAS (deb/2.8/UI)" 5
xpub add discourse enabling-maas.md "Enabling MAAS (deb/2.9/CLI)" 5
xpub add discourse enabling-maas.md "Enabling MAAS (deb/2.9/UI)" 5
xpub add discourse explore-maas.md "Explore MAAS (snap/2.7/CLI)" 5
xpub add discourse explore-maas.md "Explore MAAS (snap/2.7/UI)" 5
xpub add discourse explore-maas.md "Explore MAAS (snap/2.8/CLI)" 5
xpub add discourse explore-maas.md "Explore MAAS (snap/2.8/UI)" 5
xpub add discourse explore-maas.md "Explore MAAS (snap/2.9/CLI)" 5
xpub add discourse explore-maas.md "Explore MAAS (snap/2.9/UI)" 5
xpub add discourse explore-maas.md "Explore MAAS (deb/2.7/CLI)" 5
xpub add discourse explore-maas.md "Explore MAAS (deb/2.7/UI)" 5
xpub add discourse explore-maas.md "Explore MAAS (deb/2.8/CLI)" 5
xpub add discourse explore-maas.md "Explore MAAS (deb/2.8/UI)" 5
xpub add discourse explore-maas.md "Explore MAAS (deb/2.9/CLI)" 5
xpub add discourse explore-maas.md "Explore MAAS (deb/2.9/UI)" 5
xpub add discourse give-me-an-example-of-maas.md "Give me an example of MAAS (snap/2.7/CLI)" 5
xpub add discourse give-me-an-example-of-maas.md "Give me an example of MAAS (snap/2.7/UI)" 5
xpub add discourse give-me-an-example-of-maas.md "Give me an example of MAAS (snap/2.8/CLI)" 5
xpub add discourse give-me-an-example-of-maas.md "Give me an example of MAAS (snap/2.8/UI)" 5
xpub add discourse give-me-an-example-of-maas.md "Give me an example of MAAS (snap/2.9/CLI)" 5
xpub add discourse give-me-an-example-of-maas.md "Give me an example of MAAS (snap/2.9/UI)" 5
xpub add discourse give-me-an-example-of-maas.md "Give me an example of MAAS (deb/2.7/CLI)" 5
xpub add discourse give-me-an-example-of-maas.md "Give me an example of MAAS (deb/2.7/UI)" 5
xpub add discourse give-me-an-example-of-maas.md "Give me an example of MAAS (deb/2.8/CLI)" 5
xpub add discourse give-me-an-example-of-maas.md "Give me an example of MAAS (deb/2.8/UI)" 5
xpub add discourse give-me-an-example-of-maas.md "Give me an example of MAAS (deb/2.9/CLI)" 5
xpub add discourse give-me-an-example-of-maas.md "Give me an example of MAAS (deb/2.9/UI)" 5
xpub add discourse hardening-your-maas-installation.md "Hardening your MAAS installation (snap/2.7/CLI)" 5
xpub add discourse hardening-your-maas-installation.md "Hardening your MAAS installation (snap/2.7/UI)" 5
xpub add discourse hardening-your-maas-installation.md "Hardening your MAAS installation (snap/2.8/CLI)" 5
xpub add discourse hardening-your-maas-installation.md "Hardening your MAAS installation (snap/2.8/UI)" 5
xpub add discourse hardening-your-maas-installation.md "Hardening your MAAS installation (snap/2.9/CLI)" 5
xpub add discourse hardening-your-maas-installation.md "Hardening your MAAS installation (snap/2.9/UI)" 5
xpub add discourse hardening-your-maas-installation.md "Hardening your MAAS installation (deb/2.7/CLI)" 5
xpub add discourse hardening-your-maas-installation.md "Hardening your MAAS installation (deb/2.7/UI)" 5
xpub add discourse hardening-your-maas-installation.md "Hardening your MAAS installation (deb/2.8/CLI)" 5
xpub add discourse hardening-your-maas-installation.md "Hardening your MAAS installation (deb/2.8/UI)" 5
xpub add discourse hardening-your-maas-installation.md "Hardening your MAAS installation (deb/2.9/CLI)" 5
xpub add discourse hardening-your-maas-installation.md "Hardening your MAAS installation (deb/2.9/UI)" 5
xpub add discourse hardware-testing.md "Hardware testing (snap/2.7/CLI)" 5
xpub add discourse hardware-testing.md "Hardware testing (snap/2.7/UI)" 5
xpub add discourse hardware-testing.md "Hardware testing (snap/2.8/CLI)" 5
xpub add discourse hardware-testing.md "Hardware testing (snap/2.8/UI)" 5
xpub add discourse hardware-testing.md "Hardware testing (snap/2.9/CLI)" 5
xpub add discourse hardware-testing.md "Hardware testing (snap/2.9/UI)" 5
xpub add discourse hardware-testing.md "Hardware testing (deb/2.7/CLI)" 5
xpub add discourse hardware-testing.md "Hardware testing (deb/2.7/UI)" 5
xpub add discourse hardware-testing.md "Hardware testing (deb/2.8/CLI)" 5
xpub add discourse hardware-testing.md "Hardware testing (deb/2.8/UI)" 5
xpub add discourse hardware-testing.md "Hardware testing (deb/2.9/CLI)" 5
xpub add discourse hardware-testing.md "Hardware testing (deb/2.9/UI)" 5
xpub add discourse high-availability.md "High availability (snap/2.7/CLI)" 5
xpub add discourse high-availability.md "High availability (snap/2.7/UI)" 5
xpub add discourse high-availability.md "High availability (snap/2.8/CLI)" 5
xpub add discourse high-availability.md "High availability (snap/2.8/UI)" 5
xpub add discourse high-availability.md "High availability (snap/2.9/CLI)" 5
xpub add discourse high-availability.md "High availability (snap/2.9/UI)" 5
xpub add discourse high-availability.md "High availability (deb/2.7/CLI)" 5
xpub add discourse high-availability.md "High availability (deb/2.7/UI)" 5
xpub add discourse high-availability.md "High availability (deb/2.8/CLI)" 5
xpub add discourse high-availability.md "High availability (deb/2.8/UI)" 5
xpub add discourse high-availability.md "High availability (deb/2.9/CLI)" 5
xpub add discourse high-availability.md "High availability (deb/2.9/UI)" 5
xpub add discourse images.md "Images (snap/2.7/CLI)" 5
xpub add discourse images.md "Images (snap/2.7/UI)" 5
xpub add discourse images.md "Images (snap/2.8/CLI)" 5
xpub add discourse images.md "Images (snap/2.8/UI)" 5
xpub add discourse images.md "Images (snap/2.9/CLI)" 5
xpub add discourse images.md "Images (snap/2.9/UI)" 5
xpub add discourse images.md "Images (deb/2.7/CLI)" 5
xpub add discourse images.md "Images (deb/2.7/UI)" 5
xpub add discourse images.md "Images (deb/2.8/CLI)" 5
xpub add discourse images.md "Images (deb/2.8/UI)" 5
xpub add discourse images.md "Images (deb/2.9/CLI)" 5
xpub add discourse images.md "Images (deb/2.9/UI)" 5
xpub add discourse interactive-search.md "Interactive search (snap/2.7/CLI)" 5
xpub add discourse interactive-search.md "Interactive search (snap/2.7/UI)" 5
xpub add discourse interactive-search.md "Interactive search (snap/2.8/CLI)" 5
xpub add discourse interactive-search.md "Interactive search (snap/2.8/UI)" 5
xpub add discourse interactive-search.md "Interactive search (snap/2.9/CLI)" 5
xpub add discourse interactive-search.md "Interactive search (snap/2.9/UI)" 5
xpub add discourse interactive-search.md "Interactive search (deb/2.7/CLI)" 5
xpub add discourse interactive-search.md "Interactive search (deb/2.7/UI)" 5
xpub add discourse interactive-search.md "Interactive search (deb/2.8/CLI)" 5
xpub add discourse interactive-search.md "Interactive search (deb/2.8/UI)" 5
xpub add discourse interactive-search.md "Interactive search (deb/2.9/CLI)" 5
xpub add discourse interactive-search.md "Interactive search (deb/2.9/UI)" 5
xpub add discourse introduction-to-controllers.md "Introduction to controllers (snap/2.7/CLI)" 5
xpub add discourse introduction-to-controllers.md "Introduction to controllers (snap/2.7/UI)" 5
xpub add discourse introduction-to-controllers.md "Introduction to controllers (snap/2.8/CLI)" 5
xpub add discourse introduction-to-controllers.md "Introduction to controllers (snap/2.8/UI)" 5
xpub add discourse introduction-to-controllers.md "Introduction to controllers (snap/2.9/CLI)" 5
xpub add discourse introduction-to-controllers.md "Introduction to controllers (snap/2.9/UI)" 5
xpub add discourse introduction-to-controllers.md "Introduction to controllers (deb/2.7/CLI)" 5
xpub add discourse introduction-to-controllers.md "Introduction to controllers (deb/2.7/UI)" 5
xpub add discourse introduction-to-controllers.md "Introduction to controllers (deb/2.8/CLI)" 5
xpub add discourse introduction-to-controllers.md "Introduction to controllers (deb/2.8/UI)" 5
xpub add discourse introduction-to-controllers.md "Introduction to controllers (deb/2.9/CLI)" 5
xpub add discourse introduction-to-controllers.md "Introduction to controllers (deb/2.9/UI)" 5
xpub add discourse introduction-to-machines.md "Introduction to machines (snap/2.7/CLI)" 5
xpub add discourse introduction-to-machines.md "Introduction to machines (snap/2.7/UI)" 5
xpub add discourse introduction-to-machines.md "Introduction to machines (snap/2.8/CLI)" 5
xpub add discourse introduction-to-machines.md "Introduction to machines (snap/2.8/UI)" 5
xpub add discourse introduction-to-machines.md "Introduction to machines (snap/2.9/CLI)" 5
xpub add discourse introduction-to-machines.md "Introduction to machines (snap/2.9/UI)" 5
xpub add discourse introduction-to-machines.md "Introduction to machines (deb/2.7/CLI)" 5
xpub add discourse introduction-to-machines.md "Introduction to machines (deb/2.7/UI)" 5
xpub add discourse introduction-to-machines.md "Introduction to machines (deb/2.8/CLI)" 5
xpub add discourse introduction-to-machines.md "Introduction to machines (deb/2.8/UI)" 5
xpub add discourse introduction-to-machines.md "Introduction to machines (deb/2.9/CLI)" 5
xpub add discourse introduction-to-machines.md "Introduction to machines (deb/2.9/UI)" 5
xpub add discourse introduction-to-vm-hosting.md "Introduction to VM hosting (snap/2.7/CLI)" 5
xpub add discourse introduction-to-vm-hosting.md "Introduction to VM hosting (snap/2.7/UI)" 5
xpub add discourse introduction-to-vm-hosting.md "Introduction to VM hosting (snap/2.8/CLI)" 5
xpub add discourse introduction-to-vm-hosting.md "Introduction to VM hosting (snap/2.8/UI)" 5
xpub add discourse introduction-to-vm-hosting.md "Introduction to VM hosting (snap/2.9/CLI)" 5
xpub add discourse introduction-to-vm-hosting.md "Introduction to VM hosting (snap/2.9/UI)" 5
xpub add discourse introduction-to-vm-hosting.md "Introduction to VM hosting (deb/2.7/CLI)" 5
xpub add discourse introduction-to-vm-hosting.md "Introduction to VM hosting (deb/2.7/UI)" 5
xpub add discourse introduction-to-vm-hosting.md "Introduction to VM hosting (deb/2.8/CLI)" 5
xpub add discourse introduction-to-vm-hosting.md "Introduction to VM hosting (deb/2.8/UI)" 5
xpub add discourse introduction-to-vm-hosting.md "Introduction to VM hosting (deb/2.9/CLI)" 5
xpub add discourse introduction-to-vm-hosting.md "Introduction to VM hosting (deb/2.9/UI)" 5
xpub add discourse ip-ranges.md "IP ranges (snap/2.7/CLI)" 5
xpub add discourse ip-ranges.md "IP ranges (snap/2.7/UI)" 5
xpub add discourse ip-ranges.md "IP ranges (snap/2.8/CLI)" 5
xpub add discourse ip-ranges.md "IP ranges (snap/2.8/UI)" 5
xpub add discourse ip-ranges.md "IP ranges (snap/2.9/CLI)" 5
xpub add discourse ip-ranges.md "IP ranges (snap/2.9/UI)" 5
xpub add discourse ip-ranges.md "IP ranges (deb/2.7/CLI)" 5
xpub add discourse ip-ranges.md "IP ranges (deb/2.7/UI)" 5
xpub add discourse ip-ranges.md "IP ranges (deb/2.8/CLI)" 5
xpub add discourse ip-ranges.md "IP ranges (deb/2.8/UI)" 5
xpub add discourse ip-ranges.md "IP ranges (deb/2.9/CLI)" 5
xpub add discourse ip-ranges.md "IP ranges (deb/2.9/UI)" 5
xpub add discourse ipv6-addressing.md "Ipv6 addressing (snap/2.7/CLI)" 5
xpub add discourse ipv6-addressing.md "Ipv6 addressing (snap/2.7/UI)" 5
xpub add discourse ipv6-addressing.md "Ipv6 addressing (snap/2.8/CLI)" 5
xpub add discourse ipv6-addressing.md "Ipv6 addressing (snap/2.8/UI)" 5
xpub add discourse ipv6-addressing.md "Ipv6 addressing (snap/2.9/CLI)" 5
xpub add discourse ipv6-addressing.md "Ipv6 addressing (snap/2.9/UI)" 5
xpub add discourse ipv6-addressing.md "Ipv6 addressing (deb/2.7/CLI)" 5
xpub add discourse ipv6-addressing.md "Ipv6 addressing (deb/2.7/UI)" 5
xpub add discourse ipv6-addressing.md "Ipv6 addressing (deb/2.8/CLI)" 5
xpub add discourse ipv6-addressing.md "Ipv6 addressing (deb/2.8/UI)" 5
xpub add discourse ipv6-addressing.md "Ipv6 addressing (deb/2.9/CLI)" 5
xpub add discourse ipv6-addressing.md "Ipv6 addressing (deb/2.9/UI)" 5
xpub add discourse kernel-boot-options.md "Kernel boot options (snap/2.7/CLI)" 5
xpub add discourse kernel-boot-options.md "Kernel boot options (snap/2.7/UI)" 5
xpub add discourse kernel-boot-options.md "Kernel boot options (snap/2.8/CLI)" 5
xpub add discourse kernel-boot-options.md "Kernel boot options (snap/2.8/UI)" 5
xpub add discourse kernel-boot-options.md "Kernel boot options (snap/2.9/CLI)" 5
xpub add discourse kernel-boot-options.md "Kernel boot options (snap/2.9/UI)" 5
xpub add discourse kernel-boot-options.md "Kernel boot options (deb/2.7/CLI)" 5
xpub add discourse kernel-boot-options.md "Kernel boot options (deb/2.7/UI)" 5
xpub add discourse kernel-boot-options.md "Kernel boot options (deb/2.8/CLI)" 5
xpub add discourse kernel-boot-options.md "Kernel boot options (deb/2.8/UI)" 5
xpub add discourse kernel-boot-options.md "Kernel boot options (deb/2.9/CLI)" 5
xpub add discourse kernel-boot-options.md "Kernel boot options (deb/2.9/UI)" 5
xpub add discourse language-details-contributing-to-maas-docs.md "Language details contributing to MAAS docs (snap/2.7/CLI)" 5
xpub add discourse language-details-contributing-to-maas-docs.md "Language details contributing to MAAS docs (snap/2.7/UI)" 5
xpub add discourse language-details-contributing-to-maas-docs.md "Language details contributing to MAAS docs (snap/2.8/CLI)" 5
xpub add discourse language-details-contributing-to-maas-docs.md "Language details contributing to MAAS docs (snap/2.8/UI)" 5
xpub add discourse language-details-contributing-to-maas-docs.md "Language details contributing to MAAS docs (snap/2.9/CLI)" 5
xpub add discourse language-details-contributing-to-maas-docs.md "Language details contributing to MAAS docs (snap/2.9/UI)" 5
xpub add discourse language-details-contributing-to-maas-docs.md "Language details contributing to MAAS docs (deb/2.7/CLI)" 5
xpub add discourse language-details-contributing-to-maas-docs.md "Language details contributing to MAAS docs (deb/2.7/UI)" 5
xpub add discourse language-details-contributing-to-maas-docs.md "Language details contributing to MAAS docs (deb/2.8/CLI)" 5
xpub add discourse language-details-contributing-to-maas-docs.md "Language details contributing to MAAS docs (deb/2.8/UI)" 5
xpub add discourse language-details-contributing-to-maas-docs.md "Language details contributing to MAAS docs (deb/2.9/CLI)" 5
xpub add discourse language-details-contributing-to-maas-docs.md "Language details contributing to MAAS docs (deb/2.9/UI)" 5
xpub add discourse local-image-mirror.md "Local image mirror (snap/2.7/CLI)" 5
xpub add discourse local-image-mirror.md "Local image mirror (snap/2.7/UI)" 5
xpub add discourse local-image-mirror.md "Local image mirror (snap/2.8/CLI)" 5
xpub add discourse local-image-mirror.md "Local image mirror (snap/2.8/UI)" 5
xpub add discourse local-image-mirror.md "Local image mirror (snap/2.9/CLI)" 5
xpub add discourse local-image-mirror.md "Local image mirror (snap/2.9/UI)" 5
xpub add discourse local-image-mirror.md "Local image mirror (deb/2.7/CLI)" 5
xpub add discourse local-image-mirror.md "Local image mirror (deb/2.7/UI)" 5
xpub add discourse local-image-mirror.md "Local image mirror (deb/2.8/CLI)" 5
xpub add discourse local-image-mirror.md "Local image mirror (deb/2.8/UI)" 5
xpub add discourse local-image-mirror.md "Local image mirror (deb/2.9/CLI)" 5
xpub add discourse local-image-mirror.md "Local image mirror (deb/2.9/UI)" 5
xpub add discourse maas-cli.md "MAAS CLI (snap/2.7/CLI)" 5
xpub add discourse maas-cli.md "MAAS CLI (snap/2.7/UI)" 5
xpub add discourse maas-cli.md "MAAS CLI (snap/2.8/CLI)" 5
xpub add discourse maas-cli.md "MAAS CLI (snap/2.8/UI)" 5
xpub add discourse maas-cli.md "MAAS CLI (snap/2.9/CLI)" 5
xpub add discourse maas-cli.md "MAAS CLI (snap/2.9/UI)" 5
xpub add discourse maas-cli.md "MAAS CLI (deb/2.7/CLI)" 5
xpub add discourse maas-cli.md "MAAS CLI (deb/2.7/UI)" 5
xpub add discourse maas-cli.md "MAAS CLI (deb/2.8/CLI)" 5
xpub add discourse maas-cli.md "MAAS CLI (deb/2.8/UI)" 5
xpub add discourse maas-cli.md "MAAS CLI (deb/2.9/CLI)" 5
xpub add discourse maas-cli.md "MAAS CLI (deb/2.9/UI)" 5
xpub add discourse maas-communication.md "MAAS communication (snap/2.7/CLI)" 5
xpub add discourse maas-communication.md "MAAS communication (snap/2.7/UI)" 5
xpub add discourse maas-communication.md "MAAS communication (snap/2.8/CLI)" 5
xpub add discourse maas-communication.md "MAAS communication (snap/2.8/UI)" 5
xpub add discourse maas-communication.md "MAAS communication (snap/2.9/CLI)" 5
xpub add discourse maas-communication.md "MAAS communication (snap/2.9/UI)" 5
xpub add discourse maas-communication.md "MAAS communication (deb/2.7/CLI)" 5
xpub add discourse maas-communication.md "MAAS communication (deb/2.7/UI)" 5
xpub add discourse maas-communication.md "MAAS communication (deb/2.8/CLI)" 5
xpub add discourse maas-communication.md "MAAS communication (deb/2.8/UI)" 5
xpub add discourse maas-communication.md "MAAS communication (deb/2.9/CLI)" 5
xpub add discourse maas-communication.md "MAAS communication (deb/2.9/UI)" 5
xpub add discourse maas-documentation.md "MAAS documentation (snap/2.7/CLI)" 5
xpub add discourse maas-documentation.md "MAAS documentation (snap/2.7/UI)" 5
xpub add discourse maas-documentation.md "MAAS documentation (snap/2.8/CLI)" 5
xpub add discourse maas-documentation.md "MAAS documentation (snap/2.8/UI)" 5
xpub add discourse maas-documentation.md "MAAS documentation (snap/2.9/CLI)" 5
xpub add discourse maas-documentation.md "MAAS documentation (snap/2.9/UI)" 5
xpub add discourse maas-documentation.md "MAAS documentation (deb/2.7/CLI)" 5
xpub add discourse maas-documentation.md "MAAS documentation (deb/2.7/UI)" 5
xpub add discourse maas-documentation.md "MAAS documentation (deb/2.8/CLI)" 5
xpub add discourse maas-documentation.md "MAAS documentation (deb/2.8/UI)" 5
xpub add discourse maas-documentation.md "MAAS documentation (deb/2.9/CLI)" 5
xpub add discourse maas-documentation.md "MAAS documentation (deb/2.9/UI)" 5
xpub add discourse maas-image-builder.md "MAAS image builder (snap/2.7/CLI)" 5
xpub add discourse maas-image-builder.md "MAAS image builder (snap/2.7/UI)" 5
xpub add discourse maas-image-builder.md "MAAS image builder (snap/2.8/CLI)" 5
xpub add discourse maas-image-builder.md "MAAS image builder (snap/2.8/UI)" 5
xpub add discourse maas-image-builder.md "MAAS image builder (snap/2.9/CLI)" 5
xpub add discourse maas-image-builder.md "MAAS image builder (snap/2.9/UI)" 5
xpub add discourse maas-image-builder.md "MAAS image builder (deb/2.7/CLI)" 5
xpub add discourse maas-image-builder.md "MAAS image builder (deb/2.7/UI)" 5
xpub add discourse maas-image-builder.md "MAAS image builder (deb/2.8/CLI)" 5
xpub add discourse maas-image-builder.md "MAAS image builder (deb/2.8/UI)" 5
xpub add discourse maas-image-builder.md "MAAS image builder (deb/2.9/CLI)" 5
xpub add discourse maas-image-builder.md "MAAS image builder (deb/2.9/UI)" 5
xpub add discourse maas-logging.md "MAAS logging (snap/2.7/CLI)" 5
xpub add discourse maas-logging.md "MAAS logging (snap/2.7/UI)" 5
xpub add discourse maas-logging.md "MAAS logging (snap/2.8/CLI)" 5
xpub add discourse maas-logging.md "MAAS logging (snap/2.8/UI)" 5
xpub add discourse maas-logging.md "MAAS logging (snap/2.9/CLI)" 5
xpub add discourse maas-logging.md "MAAS logging (snap/2.9/UI)" 5
xpub add discourse maas-logging.md "MAAS logging (deb/2.7/CLI)" 5
xpub add discourse maas-logging.md "MAAS logging (deb/2.7/UI)" 5
xpub add discourse maas-logging.md "MAAS logging (deb/2.8/CLI)" 5
xpub add discourse maas-logging.md "MAAS logging (deb/2.8/UI)" 5
xpub add discourse maas-logging.md "MAAS logging (deb/2.9/CLI)" 5
xpub add discourse maas-logging.md "MAAS logging (deb/2.9/UI)" 5
xpub add discourse maas-requirements.md "MAAS requirements (snap/2.7/CLI)" 5
xpub add discourse maas-requirements.md "MAAS requirements (snap/2.7/UI)" 5
xpub add discourse maas-requirements.md "MAAS requirements (snap/2.8/CLI)" 5
xpub add discourse maas-requirements.md "MAAS requirements (snap/2.8/UI)" 5
xpub add discourse maas-requirements.md "MAAS requirements (snap/2.9/CLI)" 5
xpub add discourse maas-requirements.md "MAAS requirements (snap/2.9/UI)" 5
xpub add discourse maas-requirements.md "MAAS requirements (deb/2.7/CLI)" 5
xpub add discourse maas-requirements.md "MAAS requirements (deb/2.7/UI)" 5
xpub add discourse maas-requirements.md "MAAS requirements (deb/2.8/CLI)" 5
xpub add discourse maas-requirements.md "MAAS requirements (deb/2.8/UI)" 5
xpub add discourse maas-requirements.md "MAAS requirements (deb/2.9/CLI)" 5
xpub add discourse maas-requirements.md "MAAS requirements (deb/2.9/UI)" 5
xpub add discourse maas-tags.md "MAAS tags (snap/2.7/CLI)" 5
xpub add discourse maas-tags.md "MAAS tags (snap/2.7/UI)" 5
xpub add discourse maas-tags.md "MAAS tags (snap/2.8/CLI)" 5
xpub add discourse maas-tags.md "MAAS tags (snap/2.8/UI)" 5
xpub add discourse maas-tags.md "MAAS tags (snap/2.9/CLI)" 5
xpub add discourse maas-tags.md "MAAS tags (snap/2.9/UI)" 5
xpub add discourse maas-tags.md "MAAS tags (deb/2.7/CLI)" 5
xpub add discourse maas-tags.md "MAAS tags (deb/2.7/UI)" 5
xpub add discourse maas-tags.md "MAAS tags (deb/2.8/CLI)" 5
xpub add discourse maas-tags.md "MAAS tags (deb/2.8/UI)" 5
xpub add discourse maas-tags.md "MAAS tags (deb/2.9/CLI)" 5
xpub add discourse maas-tags.md "MAAS tags (deb/2.9/UI)" 5
xpub add discourse managing-dhcp.md "Managing DHCP (snap/2.7/CLI)" 5
xpub add discourse managing-dhcp.md "Managing DHCP (snap/2.7/UI)" 5
xpub add discourse managing-dhcp.md "Managing DHCP (snap/2.8/CLI)" 5
xpub add discourse managing-dhcp.md "Managing DHCP (snap/2.8/UI)" 5
xpub add discourse managing-dhcp.md "Managing DHCP (snap/2.9/CLI)" 5
xpub add discourse managing-dhcp.md "Managing DHCP (snap/2.9/UI)" 5
xpub add discourse managing-dhcp.md "Managing DHCP (deb/2.7/CLI)" 5
xpub add discourse managing-dhcp.md "Managing DHCP (deb/2.7/UI)" 5
xpub add discourse managing-dhcp.md "Managing DHCP (deb/2.8/CLI)" 5
xpub add discourse managing-dhcp.md "Managing DHCP (deb/2.8/UI)" 5
xpub add discourse managing-dhcp.md "Managing DHCP (deb/2.9/CLI)" 5
xpub add discourse managing-dhcp.md "Managing DHCP (deb/2.9/UI)" 5
xpub add discourse managing-stp.md "Managing STP (snap/2.7/CLI)" 5
xpub add discourse managing-stp.md "Managing STP (snap/2.7/UI)" 5
xpub add discourse managing-stp.md "Managing STP (snap/2.8/CLI)" 5
xpub add discourse managing-stp.md "Managing STP (snap/2.8/UI)" 5
xpub add discourse managing-stp.md "Managing STP (snap/2.9/CLI)" 5
xpub add discourse managing-stp.md "Managing STP (snap/2.9/UI)" 5
xpub add discourse managing-stp.md "Managing STP (deb/2.7/CLI)" 5
xpub add discourse managing-stp.md "Managing STP (deb/2.7/UI)" 5
xpub add discourse managing-stp.md "Managing STP (deb/2.8/CLI)" 5
xpub add discourse managing-stp.md "Managing STP (deb/2.8/UI)" 5
xpub add discourse managing-stp.md "Managing STP (deb/2.9/CLI)" 5
xpub add discourse managing-stp.md "Managing STP (deb/2.9/UI)" 5
xpub add discourse network-discovery.md "Network discovery (snap/2.7/CLI)" 5
xpub add discourse network-discovery.md "Network discovery (snap/2.7/UI)" 5
xpub add discourse network-discovery.md "Network discovery (snap/2.8/CLI)" 5
xpub add discourse network-discovery.md "Network discovery (snap/2.8/UI)" 5
xpub add discourse network-discovery.md "Network discovery (snap/2.9/CLI)" 5
xpub add discourse network-discovery.md "Network discovery (snap/2.9/UI)" 5
xpub add discourse network-discovery.md "Network discovery (deb/2.7/CLI)" 5
xpub add discourse network-discovery.md "Network discovery (deb/2.7/UI)" 5
xpub add discourse network-discovery.md "Network discovery (deb/2.8/CLI)" 5
xpub add discourse network-discovery.md "Network discovery (deb/2.8/UI)" 5
xpub add discourse network-discovery.md "Network discovery (deb/2.9/CLI)" 5
xpub add discourse network-discovery.md "Network discovery (deb/2.9/UI)" 5
xpub add discourse network-testing.md "network Testing (snap/2.7/CLI)" 5
xpub add discourse network-testing.md "network Testing (snap/2.7/UI)" 5
xpub add discourse network-testing.md "network Testing (snap/2.8/CLI)" 5
xpub add discourse network-testing.md "network Testing (snap/2.8/UI)" 5
xpub add discourse network-testing.md "network Testing (snap/2.9/CLI)" 5
xpub add discourse network-testing.md "network Testing (snap/2.9/UI)" 5
xpub add discourse network-testing.md "network Testing (deb/2.7/CLI)" 5
xpub add discourse network-testing.md "network Testing (deb/2.7/UI)" 5
xpub add discourse network-testing.md "network Testing (deb/2.8/CLI)" 5
xpub add discourse network-testing.md "network Testing (deb/2.8/UI)" 5
xpub add discourse network-testing.md "network Testing (deb/2.9/CLI)" 5
xpub add discourse network-testing.md "network Testing (deb/2.9/UI)" 5
xpub add discourse networking.md "Networking (snap/2.7/CLI)" 5
xpub add discourse networking.md "Networking (snap/2.7/UI)" 5
xpub add discourse networking.md "Networking (snap/2.8/CLI)" 5
xpub add discourse networking.md "Networking (snap/2.8/UI)" 5
xpub add discourse networking.md "Networking (snap/2.9/CLI)" 5
xpub add discourse networking.md "Networking (snap/2.9/UI)" 5
xpub add discourse networking.md "Networking (deb/2.7/CLI)" 5
xpub add discourse networking.md "Networking (deb/2.7/UI)" 5
xpub add discourse networking.md "Networking (deb/2.8/CLI)" 5
xpub add discourse networking.md "Networking (deb/2.8/UI)" 5
xpub add discourse networking.md "Networking (deb/2.9/CLI)" 5
xpub add discourse networking.md "Networking (deb/2.9/UI)" 5
xpub add discourse ntp-services.md "NTP services (snap/2.7/CLI)" 5
xpub add discourse ntp-services.md "NTP services (snap/2.7/UI)" 5
xpub add discourse ntp-services.md "NTP services (snap/2.8/CLI)" 5
xpub add discourse ntp-services.md "NTP services (snap/2.8/UI)" 5
xpub add discourse ntp-services.md "NTP services (snap/2.9/CLI)" 5
xpub add discourse ntp-services.md "NTP services (snap/2.9/UI)" 5
xpub add discourse ntp-services.md "NTP services (deb/2.7/CLI)" 5
xpub add discourse ntp-services.md "NTP services (deb/2.7/UI)" 5
xpub add discourse ntp-services.md "NTP services (deb/2.8/CLI)" 5
xpub add discourse ntp-services.md "NTP services (deb/2.8/UI)" 5
xpub add discourse ntp-services.md "NTP services (deb/2.9/CLI)" 5
xpub add discourse ntp-services.md "NTP services (deb/2.9/UI)" 5
xpub add discourse package-repositories.md "Package repositories (snap/2.7/CLI)" 5
xpub add discourse package-repositories.md "Package repositories (snap/2.7/UI)" 5
xpub add discourse package-repositories.md "Package repositories (snap/2.8/CLI)" 5
xpub add discourse package-repositories.md "Package repositories (snap/2.8/UI)" 5
xpub add discourse package-repositories.md "Package repositories (snap/2.9/CLI)" 5
xpub add discourse package-repositories.md "Package repositories (snap/2.9/UI)" 5
xpub add discourse package-repositories.md "Package repositories (deb/2.7/CLI)" 5
xpub add discourse package-repositories.md "Package repositories (deb/2.7/UI)" 5
xpub add discourse package-repositories.md "Package repositories (deb/2.8/CLI)" 5
xpub add discourse package-repositories.md "Package repositories (deb/2.8/UI)" 5
xpub add discourse package-repositories.md "Package repositories (deb/2.9/CLI)" 5
xpub add discourse package-repositories.md "Package repositories (deb/2.9/UI)" 5
xpub add discourse partitions.md "Partitions (snap/2.7/CLI)" 5
xpub add discourse partitions.md "Partitions (snap/2.7/UI)" 5
xpub add discourse partitions.md "Partitions (snap/2.8/CLI)" 5
xpub add discourse partitions.md "Partitions (snap/2.8/UI)" 5
xpub add discourse partitions.md "Partitions (snap/2.9/CLI)" 5
xpub add discourse partitions.md "Partitions (snap/2.9/UI)" 5
xpub add discourse partitions.md "Partitions (deb/2.7/CLI)" 5
xpub add discourse partitions.md "Partitions (deb/2.7/UI)" 5
xpub add discourse partitions.md "Partitions (deb/2.8/CLI)" 5
xpub add discourse partitions.md "Partitions (deb/2.8/UI)" 5
xpub add discourse partitions.md "Partitions (deb/2.9/CLI)" 5
xpub add discourse partitions.md "Partitions (deb/2.9/UI)" 5
xpub add discourse postgresql-ha-hot-standby.md "PostgreSQL HA hot standby (snap/2.7/CLI)" 5
xpub add discourse postgresql-ha-hot-standby.md "PostgreSQL HA hot standby (snap/2.7/UI)" 5
xpub add discourse postgresql-ha-hot-standby.md "PostgreSQL HA hot standby (snap/2.8/CLI)" 5
xpub add discourse postgresql-ha-hot-standby.md "PostgreSQL HA hot standby (snap/2.8/UI)" 5
xpub add discourse postgresql-ha-hot-standby.md "PostgreSQL HA hot standby (snap/2.9/CLI)" 5
xpub add discourse postgresql-ha-hot-standby.md "PostgreSQL HA hot standby (snap/2.9/UI)" 5
xpub add discourse postgresql-ha-hot-standby.md "PostgreSQL HA hot standby (deb/2.7/CLI)" 5
xpub add discourse postgresql-ha-hot-standby.md "PostgreSQL HA hot standby (deb/2.7/UI)" 5
xpub add discourse postgresql-ha-hot-standby.md "PostgreSQL HA hot standby (deb/2.8/CLI)" 5
xpub add discourse postgresql-ha-hot-standby.md "PostgreSQL HA hot standby (deb/2.8/UI)" 5
xpub add discourse postgresql-ha-hot-standby.md "PostgreSQL HA hot standby (deb/2.9/CLI)" 5
xpub add discourse postgresql-ha-hot-standby.md "PostgreSQL HA hot standby (deb/2.9/UI)" 5
xpub add discourse power-management.md "Power management (snap/2.7/CLI)" 5
xpub add discourse power-management.md "Power management (snap/2.7/UI)" 5
xpub add discourse power-management.md "Power management (snap/2.8/CLI)" 5
xpub add discourse power-management.md "Power management (snap/2.8/UI)" 5
xpub add discourse power-management.md "Power management (snap/2.9/CLI)" 5
xpub add discourse power-management.md "Power management (snap/2.9/UI)" 5
xpub add discourse power-management.md "Power management (deb/2.7/CLI)" 5
xpub add discourse power-management.md "Power management (deb/2.7/UI)" 5
xpub add discourse power-management.md "Power management (deb/2.8/CLI)" 5
xpub add discourse power-management.md "Power management (deb/2.8/UI)" 5
xpub add discourse power-management.md "Power management (deb/2.9/CLI)" 5
xpub add discourse power-management.md "Power management (deb/2.9/UI)" 5
xpub add discourse prometheus-metrics.md "Prometheus metrics (snap/2.7/CLI)" 5
xpub add discourse prometheus-metrics.md "Prometheus metrics (snap/2.7/UI)" 5
xpub add discourse prometheus-metrics.md "Prometheus metrics (snap/2.8/CLI)" 5
xpub add discourse prometheus-metrics.md "Prometheus metrics (snap/2.8/UI)" 5
xpub add discourse prometheus-metrics.md "Prometheus metrics (snap/2.9/CLI)" 5
xpub add discourse prometheus-metrics.md "Prometheus metrics (snap/2.9/UI)" 5
xpub add discourse prometheus-metrics.md "Prometheus metrics (deb/2.7/CLI)" 5
xpub add discourse prometheus-metrics.md "Prometheus metrics (deb/2.7/UI)" 5
xpub add discourse prometheus-metrics.md "Prometheus metrics (deb/2.8/CLI)" 5
xpub add discourse prometheus-metrics.md "Prometheus metrics (deb/2.8/UI)" 5
xpub add discourse prometheus-metrics.md "Prometheus metrics (deb/2.9/CLI)" 5
xpub add discourse prometheus-metrics.md "Prometheus metrics (deb/2.9/UI)" 5
xpub add discourse proxy.md "Proxy (snap/2.7/CLI)" 5
xpub add discourse proxy.md "Proxy (snap/2.7/UI)" 5
xpub add discourse proxy.md "Proxy (snap/2.8/CLI)" 5
xpub add discourse proxy.md "Proxy (snap/2.8/UI)" 5
xpub add discourse proxy.md "Proxy (snap/2.9/CLI)" 5
xpub add discourse proxy.md "Proxy (snap/2.9/UI)" 5
xpub add discourse proxy.md "Proxy (deb/2.7/CLI)" 5
xpub add discourse proxy.md "Proxy (deb/2.7/UI)" 5
xpub add discourse proxy.md "Proxy (deb/2.8/CLI)" 5
xpub add discourse proxy.md "Proxy (deb/2.8/UI)" 5
xpub add discourse proxy.md "Proxy (deb/2.9/CLI)" 5
xpub add discourse proxy.md "Proxy (deb/2.9/UI)" 5
xpub add discourse python-api-client.md "Python API client (snap/2.7/CLI)" 5
xpub add discourse python-api-client.md "Python API client (snap/2.7/UI)" 5
xpub add discourse python-api-client.md "Python API client (snap/2.8/CLI)" 5
xpub add discourse python-api-client.md "Python API client (snap/2.8/UI)" 5
xpub add discourse python-api-client.md "Python API client (snap/2.9/CLI)" 5
xpub add discourse python-api-client.md "Python API client (snap/2.9/UI)" 5
xpub add discourse python-api-client.md "Python API client (deb/2.7/CLI)" 5
xpub add discourse python-api-client.md "Python API client (deb/2.7/UI)" 5
xpub add discourse python-api-client.md "Python API client (deb/2.8/CLI)" 5
xpub add discourse python-api-client.md "Python API client (deb/2.8/UI)" 5
xpub add discourse python-api-client.md "Python API client (deb/2.9/CLI)" 5
xpub add discourse python-api-client.md "Python API client (deb/2.9/UI)" 5
xpub add discourse rack-controllers.md "Rack controllers (snap/2.7/CLI)" 5
xpub add discourse rack-controllers.md "Rack controllers (snap/2.7/UI)" 5
xpub add discourse rack-controllers.md "Rack controllers (snap/2.8/CLI)" 5
xpub add discourse rack-controllers.md "Rack controllers (snap/2.8/UI)" 5
xpub add discourse rack-controllers.md "Rack controllers (snap/2.9/CLI)" 5
xpub add discourse rack-controllers.md "Rack controllers (snap/2.9/UI)" 5
xpub add discourse rack-controllers.md "Rack controllers (deb/2.7/CLI)" 5
xpub add discourse rack-controllers.md "Rack controllers (deb/2.7/UI)" 5
xpub add discourse rack-controllers.md "Rack controllers (deb/2.8/CLI)" 5
xpub add discourse rack-controllers.md "Rack controllers (deb/2.8/UI)" 5
xpub add discourse rack-controllers.md "Rack controllers (deb/2.9/CLI)" 5
xpub add discourse rack-controllers.md "Rack controllers (deb/2.9/UI)" 5
xpub add discourse rad-menu-testing.md "RAD menu testing (snap/2.7/CLI)" 5
xpub add discourse rad-menu-testing.md "RAD menu testing (snap/2.7/UI)" 5
xpub add discourse rad-menu-testing.md "RAD menu testing (snap/2.8/CLI)" 5
xpub add discourse rad-menu-testing.md "RAD menu testing (snap/2.8/UI)" 5
xpub add discourse rad-menu-testing.md "RAD menu testing (snap/2.9/CLI)" 5
xpub add discourse rad-menu-testing.md "RAD menu testing (snap/2.9/UI)" 5
xpub add discourse rad-menu-testing.md "RAD menu testing (deb/2.7/CLI)" 5
xpub add discourse rad-menu-testing.md "RAD menu testing (deb/2.7/UI)" 5
xpub add discourse rad-menu-testing.md "RAD menu testing (deb/2.8/CLI)" 5
xpub add discourse rad-menu-testing.md "RAD menu testing (deb/2.8/UI)" 5
xpub add discourse rad-menu-testing.md "RAD menu testing (deb/2.9/CLI)" 5
xpub add discourse rad-menu-testing.md "RAD menu testing (deb/2.9/UI)" 5
xpub add discourse region-controllers.md "Region controllers (snap/2.7/CLI)" 5
xpub add discourse region-controllers.md "Region controllers (snap/2.7/UI)" 5
xpub add discourse region-controllers.md "Region controllers (snap/2.8/CLI)" 5
xpub add discourse region-controllers.md "Region controllers (snap/2.8/UI)" 5
xpub add discourse region-controllers.md "Region controllers (snap/2.9/CLI)" 5
xpub add discourse region-controllers.md "Region controllers (snap/2.9/UI)" 5
xpub add discourse region-controllers.md "Region controllers (deb/2.7/CLI)" 5
xpub add discourse region-controllers.md "Region controllers (deb/2.7/UI)" 5
xpub add discourse region-controllers.md "Region controllers (deb/2.8/CLI)" 5
xpub add discourse region-controllers.md "Region controllers (deb/2.8/UI)" 5
xpub add discourse region-controllers.md "Region controllers (deb/2.9/CLI)" 5
xpub add discourse region-controllers.md "Region controllers (deb/2.9/UI)" 5
xpub add discourse resource-pools.md "Resource pools (snap/2.7/CLI)" 5
xpub add discourse resource-pools.md "Resource pools (snap/2.7/UI)" 5
xpub add discourse resource-pools.md "Resource pools (snap/2.8/CLI)" 5
xpub add discourse resource-pools.md "Resource pools (snap/2.8/UI)" 5
xpub add discourse resource-pools.md "Resource pools (snap/2.9/CLI)" 5
xpub add discourse resource-pools.md "Resource pools (snap/2.9/UI)" 5
xpub add discourse resource-pools.md "Resource pools (deb/2.7/CLI)" 5
xpub add discourse resource-pools.md "Resource pools (deb/2.7/UI)" 5
xpub add discourse resource-pools.md "Resource pools (deb/2.8/CLI)" 5
xpub add discourse resource-pools.md "Resource pools (deb/2.8/UI)" 5
xpub add discourse resource-pools.md "Resource pools (deb/2.9/CLI)" 5
xpub add discourse resource-pools.md "Resource pools (deb/2.9/UI)" 5
xpub add discourse select-and-import-images.md "Select and import images (snap/2.7/CLI)" 5
xpub add discourse select-and-import-images.md "Select and import images (snap/2.7/UI)" 5
xpub add discourse select-and-import-images.md "Select and import images (snap/2.8/CLI)" 5
xpub add discourse select-and-import-images.md "Select and import images (snap/2.8/UI)" 5
xpub add discourse select-and-import-images.md "Select and import images (snap/2.9/CLI)" 5
xpub add discourse select-and-import-images.md "Select and import images (snap/2.9/UI)" 5
xpub add discourse select-and-import-images.md "Select and import images (deb/2.7/CLI)" 5
xpub add discourse select-and-import-images.md "Select and import images (deb/2.7/UI)" 5
xpub add discourse select-and-import-images.md "Select and import images (deb/2.8/CLI)" 5
xpub add discourse select-and-import-images.md "Select and import images (deb/2.8/UI)" 5
xpub add discourse select-and-import-images.md "Select and import images (deb/2.9/CLI)" 5
xpub add discourse select-and-import-images.md "Select and import images (deb/2.9/UI)" 5
xpub add discourse storage.md "Storage (snap/2.7/CLI)" 5
xpub add discourse storage.md "Storage (snap/2.7/UI)" 5
xpub add discourse storage.md "Storage (snap/2.8/CLI)" 5
xpub add discourse storage.md "Storage (snap/2.8/UI)" 5
xpub add discourse storage.md "Storage (snap/2.9/CLI)" 5
xpub add discourse storage.md "Storage (snap/2.9/UI)" 5
xpub add discourse storage.md "Storage (deb/2.7/CLI)" 5
xpub add discourse storage.md "Storage (deb/2.7/UI)" 5
xpub add discourse storage.md "Storage (deb/2.8/CLI)" 5
xpub add discourse storage.md "Storage (deb/2.8/UI)" 5
xpub add discourse storage.md "Storage (deb/2.9/CLI)" 5
xpub add discourse storage.md "Storage (deb/2.9/UI)" 5
xpub add discourse subnet-management.md "Subnet management (snap/2.7/CLI)" 5
xpub add discourse subnet-management.md "Subnet management (snap/2.7/UI)" 5
xpub add discourse subnet-management.md "Subnet management (snap/2.8/CLI)" 5
xpub add discourse subnet-management.md "Subnet management (snap/2.8/UI)" 5
xpub add discourse subnet-management.md "Subnet management (snap/2.9/CLI)" 5
xpub add discourse subnet-management.md "Subnet management (snap/2.9/UI)" 5
xpub add discourse subnet-management.md "Subnet management (deb/2.7/CLI)" 5
xpub add discourse subnet-management.md "Subnet management (deb/2.7/UI)" 5
xpub add discourse subnet-management.md "Subnet management (deb/2.8/CLI)" 5
xpub add discourse subnet-management.md "Subnet management (deb/2.8/UI)" 5
xpub add discourse subnet-management.md "Subnet management (deb/2.9/CLI)" 5
xpub add discourse subnet-management.md "Subnet management (deb/2.9/UI)" 5
xpub add discourse test-logs.md "Test logs (snap/2.7/CLI)" 5
xpub add discourse test-logs.md "Test logs (snap/2.7/UI)" 5
xpub add discourse test-logs.md "Test logs (snap/2.8/CLI)" 5
xpub add discourse test-logs.md "Test logs (snap/2.8/UI)" 5
xpub add discourse test-logs.md "Test logs (snap/2.9/CLI)" 5
xpub add discourse test-logs.md "Test logs (snap/2.9/UI)" 5
xpub add discourse test-logs.md "Test logs (deb/2.7/CLI)" 5
xpub add discourse test-logs.md "Test logs (deb/2.7/UI)" 5
xpub add discourse test-logs.md "Test logs (deb/2.8/CLI)" 5
xpub add discourse test-logs.md "Test logs (deb/2.8/UI)" 5
xpub add discourse test-logs.md "Test logs (deb/2.9/CLI)" 5
xpub add discourse test-logs.md "Test logs (deb/2.9/UI)" 5
xpub add discourse the-cli-cookbook.md "The CLI cookbook (snap/2.7/CLI)" 5
xpub add discourse the-cli-cookbook.md "The CLI cookbook (snap/2.7/UI)" 5
xpub add discourse the-cli-cookbook.md "The CLI cookbook (snap/2.8/CLI)" 5
xpub add discourse the-cli-cookbook.md "The CLI cookbook (snap/2.8/UI)" 5
xpub add discourse the-cli-cookbook.md "The CLI cookbook (snap/2.9/CLI)" 5
xpub add discourse the-cli-cookbook.md "The CLI cookbook (snap/2.9/UI)" 5
xpub add discourse the-cli-cookbook.md "The CLI cookbook (deb/2.7/CLI)" 5
xpub add discourse the-cli-cookbook.md "The CLI cookbook (deb/2.7/UI)" 5
xpub add discourse the-cli-cookbook.md "The CLI cookbook (deb/2.8/CLI)" 5
xpub add discourse the-cli-cookbook.md "The CLI cookbook (deb/2.8/UI)" 5
xpub add discourse the-cli-cookbook.md "The CLI cookbook (deb/2.9/CLI)" 5
xpub add discourse the-cli-cookbook.md "The CLI cookbook (deb/2.9/UI)" 5
xpub add discourse tips-tricks-and-traps.md "Tips tricks and traps (snap/2.7/CLI)" 5
xpub add discourse tips-tricks-and-traps.md "Tips tricks and traps (snap/2.7/UI)" 5
xpub add discourse tips-tricks-and-traps.md "Tips tricks and traps (snap/2.8/CLI)" 5
xpub add discourse tips-tricks-and-traps.md "Tips tricks and traps (snap/2.8/UI)" 5
xpub add discourse tips-tricks-and-traps.md "Tips tricks and traps (snap/2.9/CLI)" 5
xpub add discourse tips-tricks-and-traps.md "Tips tricks and traps (snap/2.9/UI)" 5
xpub add discourse tips-tricks-and-traps.md "Tips tricks and traps (deb/2.7/CLI)" 5
xpub add discourse tips-tricks-and-traps.md "Tips tricks and traps (deb/2.7/UI)" 5
xpub add discourse tips-tricks-and-traps.md "Tips tricks and traps (deb/2.8/CLI)" 5
xpub add discourse tips-tricks-and-traps.md "Tips tricks and traps (deb/2.8/UI)" 5
xpub add discourse tips-tricks-and-traps.md "Tips tricks and traps (deb/2.9/CLI)" 5
xpub add discourse tips-tricks-and-traps.md "Tips tricks and traps (deb/2.9/UI)" 5
xpub add discourse troubleshooting.md "Troubleshooting (snap/2.7/CLI)" 5
xpub add discourse troubleshooting.md "Troubleshooting (snap/2.7/UI)" 5
xpub add discourse troubleshooting.md "Troubleshooting (snap/2.8/CLI)" 5
xpub add discourse troubleshooting.md "Troubleshooting (snap/2.8/UI)" 5
xpub add discourse troubleshooting.md "Troubleshooting (snap/2.9/CLI)" 5
xpub add discourse troubleshooting.md "Troubleshooting (snap/2.9/UI)" 5
xpub add discourse troubleshooting.md "Troubleshooting (deb/2.7/CLI)" 5
xpub add discourse troubleshooting.md "Troubleshooting (deb/2.7/UI)" 5
xpub add discourse troubleshooting.md "Troubleshooting (deb/2.8/CLI)" 5
xpub add discourse troubleshooting.md "Troubleshooting (deb/2.8/UI)" 5
xpub add discourse troubleshooting.md "Troubleshooting (deb/2.9/CLI)" 5
xpub add discourse troubleshooting.md "Troubleshooting (deb/2.9/UI)" 5
xpub add discourse ubuntu-kernels.md "Ubuntu kernels (snap/2.7/CLI)" 5
xpub add discourse ubuntu-kernels.md "Ubuntu kernels (snap/2.7/UI)" 5
xpub add discourse ubuntu-kernels.md "Ubuntu kernels (snap/2.8/CLI)" 5
xpub add discourse ubuntu-kernels.md "Ubuntu kernels (snap/2.8/UI)" 5
xpub add discourse ubuntu-kernels.md "Ubuntu kernels (snap/2.9/CLI)" 5
xpub add discourse ubuntu-kernels.md "Ubuntu kernels (snap/2.9/UI)" 5
xpub add discourse ubuntu-kernels.md "Ubuntu kernels (deb/2.7/CLI)" 5
xpub add discourse ubuntu-kernels.md "Ubuntu kernels (deb/2.7/UI)" 5
xpub add discourse ubuntu-kernels.md "Ubuntu kernels (deb/2.8/CLI)" 5
xpub add discourse ubuntu-kernels.md "Ubuntu kernels (deb/2.8/UI)" 5
xpub add discourse ubuntu-kernels.md "Ubuntu kernels (deb/2.9/CLI)" 5
xpub add discourse ubuntu-kernels.md "Ubuntu kernels (deb/2.9/UI)" 5
xpub add discourse upgrading-maas.md "Upgrading MAAS (snap/2.7/CLI)" 5
xpub add discourse upgrading-maas.md "Upgrading MAAS (snap/2.7/UI)" 5
xpub add discourse upgrading-maas.md "Upgrading MAAS (snap/2.8/CLI)" 5
xpub add discourse upgrading-maas.md "Upgrading MAAS (snap/2.8/UI)" 5
xpub add discourse upgrading-maas.md "Upgrading MAAS (snap/2.9/CLI)" 5
xpub add discourse upgrading-maas.md "Upgrading MAAS (snap/2.9/UI)" 5
xpub add discourse upgrading-maas.md "Upgrading MAAS (deb/2.7/CLI)" 5
xpub add discourse upgrading-maas.md "Upgrading MAAS (deb/2.7/UI)" 5
xpub add discourse upgrading-maas.md "Upgrading MAAS (deb/2.8/CLI)" 5
xpub add discourse upgrading-maas.md "Upgrading MAAS (deb/2.8/UI)" 5
xpub add discourse upgrading-maas.md "Upgrading MAAS (deb/2.9/CLI)" 5
xpub add discourse upgrading-maas.md "Upgrading MAAS (deb/2.9/UI)" 5
xpub add discourse user-accounts.md "User accounts (snap/2.7/CLI)" 5
xpub add discourse user-accounts.md "User accounts (snap/2.7/UI)" 5
xpub add discourse user-accounts.md "User accounts (snap/2.8/CLI)" 5
xpub add discourse user-accounts.md "User accounts (snap/2.8/UI)" 5
xpub add discourse user-accounts.md "User accounts (snap/2.9/CLI)" 5
xpub add discourse user-accounts.md "User accounts (snap/2.9/UI)" 5
xpub add discourse user-accounts.md "User accounts (deb/2.7/CLI)" 5
xpub add discourse user-accounts.md "User accounts (deb/2.7/UI)" 5
xpub add discourse user-accounts.md "User accounts (deb/2.8/CLI)" 5
xpub add discourse user-accounts.md "User accounts (deb/2.8/UI)" 5
xpub add discourse user-accounts.md "User accounts (deb/2.9/CLI)" 5
xpub add discourse user-accounts.md "User accounts (deb/2.9/UI)" 5
xpub add discourse vm-host-networking.md "VM host networking (snap/2.7/CLI)" 5
xpub add discourse vm-host-networking.md "VM host networking (snap/2.7/UI)" 5
xpub add discourse vm-host-networking.md "VM host networking (snap/2.8/CLI)" 5
xpub add discourse vm-host-networking.md "VM host networking (snap/2.8/UI)" 5
xpub add discourse vm-host-networking.md "VM host networking (snap/2.9/CLI)" 5
xpub add discourse vm-host-networking.md "VM host networking (snap/2.9/UI)" 5
xpub add discourse vm-host-networking.md "VM host networking (deb/2.7/CLI)" 5
xpub add discourse vm-host-networking.md "VM host networking (deb/2.7/UI)" 5
xpub add discourse vm-host-networking.md "VM host networking (deb/2.8/CLI)" 5
xpub add discourse vm-host-networking.md "VM host networking (deb/2.8/UI)" 5
xpub add discourse vm-host-networking.md "VM host networking (deb/2.9/CLI)" 5
xpub add discourse vm-host-networking.md "VM host networking (deb/2.9/UI)" 5
xpub add discourse vm-host-storage-pools.md "VM host storage pools (snap/2.7/CLI)" 5
xpub add discourse vm-host-storage-pools.md "VM host storage pools (snap/2.7/UI)" 5
xpub add discourse vm-host-storage-pools.md "VM host storage pools (snap/2.8/CLI)" 5
xpub add discourse vm-host-storage-pools.md "VM host storage pools (snap/2.8/UI)" 5
xpub add discourse vm-host-storage-pools.md "VM host storage pools (snap/2.9/CLI)" 5
xpub add discourse vm-host-storage-pools.md "VM host storage pools (snap/2.9/UI)" 5
xpub add discourse vm-host-storage-pools.md "VM host storage pools (deb/2.7/CLI)" 5
xpub add discourse vm-host-storage-pools.md "VM host storage pools (deb/2.7/UI)" 5
xpub add discourse vm-host-storage-pools.md "VM host storage pools (deb/2.8/CLI)" 5
xpub add discourse vm-host-storage-pools.md "VM host storage pools (deb/2.8/UI)" 5
xpub add discourse vm-host-storage-pools.md "VM host storage pools (deb/2.9/CLI)" 5
xpub add discourse vm-host-storage-pools.md "VM host storage pools (deb/2.9/UI)" 5
xpub add discourse vmware-images.md "VMWare images (snap/2.7/CLI)" 5
xpub add discourse vmware-images.md "VMWare images (snap/2.7/UI)" 5
xpub add discourse vmware-images.md "VMWare images (snap/2.8/CLI)" 5
xpub add discourse vmware-images.md "VMWare images (snap/2.8/UI)" 5
xpub add discourse vmware-images.md "VMWare images (snap/2.9/CLI)" 5
xpub add discourse vmware-images.md "VMWare images (snap/2.9/UI)" 5
xpub add discourse vmware-images.md "VMWare images (deb/2.7/CLI)" 5
xpub add discourse vmware-images.md "VMWare images (deb/2.7/UI)" 5
xpub add discourse vmware-images.md "VMWare images (deb/2.8/CLI)" 5
xpub add discourse vmware-images.md "VMWare images (deb/2.8/UI)" 5
xpub add discourse vmware-images.md "VMWare images (deb/2.9/CLI)" 5
xpub add discourse vmware-images.md "VMWare images (deb/2.9/UI)" 5
xpub add discourse vmware-vmfs-datastores.md "VMWare VMFS datastores (snap/2.7/CLI)" 5
xpub add discourse vmware-vmfs-datastores.md "VMWare VMFS datastores (snap/2.7/UI)" 5
xpub add discourse vmware-vmfs-datastores.md "VMWare VMFS datastores (snap/2.8/CLI)" 5
xpub add discourse vmware-vmfs-datastores.md "VMWare VMFS datastores (snap/2.8/UI)" 5
xpub add discourse vmware-vmfs-datastores.md "VMWare VMFS datastores (snap/2.9/CLI)" 5
xpub add discourse vmware-vmfs-datastores.md "VMWare VMFS datastores (snap/2.9/UI)" 5
xpub add discourse vmware-vmfs-datastores.md "VMWare VMFS datastores (deb/2.7/CLI)" 5
xpub add discourse vmware-vmfs-datastores.md "VMWare VMFS datastores (deb/2.7/UI)" 5
xpub add discourse vmware-vmfs-datastores.md "VMWare VMFS datastores (deb/2.8/CLI)" 5
xpub add discourse vmware-vmfs-datastores.md "VMWare VMFS datastores (deb/2.8/UI)" 5
xpub add discourse vmware-vmfs-datastores.md "VMWare VMFS datastores (deb/2.9/CLI)" 5
xpub add discourse vmware-vmfs-datastores.md "VMWare VMFS datastores (deb/2.9/UI)" 5
xpub add discourse writing-guide.md "Writing guide (snap/2.7/CLI)" 5
xpub add discourse writing-guide.md "Writing guide (snap/2.7/UI)" 5
xpub add discourse writing-guide.md "Writing guide (snap/2.8/CLI)" 5
xpub add discourse writing-guide.md "Writing guide (snap/2.8/UI)" 5
xpub add discourse writing-guide.md "Writing guide (snap/2.9/CLI)" 5
xpub add discourse writing-guide.md "Writing guide (snap/2.9/UI)" 5
xpub add discourse writing-guide.md "Writing guide (deb/2.7/CLI)" 5
xpub add discourse writing-guide.md "Writing guide (deb/2.7/UI)" 5
xpub add discourse writing-guide.md "Writing guide (deb/2.8/CLI)" 5
xpub add discourse writing-guide.md "Writing guide (deb/2.8/UI)" 5
xpub add discourse writing-guide.md "Writing guide (deb/2.9/CLI)" 5
xpub add discourse writing-guide.md "Writing guide (deb/2.9/UI)" 5
xpub add discourse zone-examples.md "Zone examples (snap/2.7/CLI)" 5
xpub add discourse zone-examples.md "Zone examples (snap/2.7/UI)" 5
xpub add discourse zone-examples.md "Zone examples (snap/2.8/CLI)" 5
xpub add discourse zone-examples.md "Zone examples (snap/2.8/UI)" 5
xpub add discourse zone-examples.md "Zone examples (snap/2.9/CLI)" 5
xpub add discourse zone-examples.md "Zone examples (snap/2.9/UI)" 5
xpub add discourse zone-examples.md "Zone examples (deb/2.7/CLI)" 5
xpub add discourse zone-examples.md "Zone examples (deb/2.7/UI)" 5
xpub add discourse zone-examples.md "Zone examples (deb/2.8/CLI)" 5
xpub add discourse zone-examples.md "Zone examples (deb/2.8/UI)" 5
xpub add discourse zone-examples.md "Zone examples (deb/2.9/CLI)" 5
xpub add discourse zone-examples.md "Zone examples (deb/2.9/UI)" 5
