TARGET_DEPS := about-maas-840.md
TARGET_DEPS += accessing-maas-782.md
TARGET_DEPS += add-a-kvm-host-805.md
TARGET_DEPS += add-an-rsd-host-815.md
TARGET_DEPS += add-a-vm-host-1523.md
TARGET_DEPS += adding-a-vm-host-1549.md
TARGET_DEPS += add-machines-821.md
TARGET_DEPS += api-authentication-742.md
TARGET_DEPS += audit-event-logs-791.md
TARGET_DEPS += availability-zones-820.md
TARGET_DEPS += backup-792.md
TARGET_DEPS += block-devices-749.md
TARGET_DEPS += building-the-docs-744.md
TARGET_DEPS += cli-advanced-tasks-793.md
TARGET_DEPS += cli-commissioning-and-hardware-testing-scripts-832.md
TARGET_DEPS += cli-composable-hardware-795.md
TARGET_DEPS += cli-dhcp-snippet-management-796.md
TARGET_DEPS += cli-image-management-797.md
TARGET_DEPS += cli-interface-management-798.md
TARGET_DEPS += cli-kernel-management-799.md
TARGET_DEPS += cli-resource-pool-management-800.md
TARGET_DEPS += cli-tag-management-801.md
TARGET_DEPS += commissioning-and-hardware-testing-scripts-833.md
TARGET_DEPS += commissioning-logs-1478.md
TARGET_DEPS += commission-machines-822.md
TARGET_DEPS += common-cli-tasks-794.md
TARGET_DEPS += concepts-and-terms-785.md
TARGET_DEPS += configuration-journey-781.md
TARGET_DEPS += configure-networking-767.md
TARGET_DEPS += configuring-tls-encryption-764.md
TARGET_DEPS += contact-us-743.md
TARGET_DEPS += creating-a-custom-ubuntu-image-1652.md
TARGET_DEPS += creating-and-deleting-machines-816.md
TARGET_DEPS += creating-and-deleting-vms-806.md
TARGET_DEPS += custom-machine-setup-824.md
TARGET_DEPS += deploy-machines-825.md
TARGET_DEPS += disc-stats.md
TARGET_DEPS += disk-erasure-774.md
TARGET_DEPS += documentation-index-839.md
TARGET_DEPS += explore-maas-787.md
TARGET_DEPS += getting-help-838.md
TARGET_DEPS += give-me-an-example-of-maas-1314.md
TARGET_DEPS += hardening-your-maas-installation-1381.md
TARGET_DEPS += hardware-testing-826.md
TARGET_DEPS += high-availability-804.md
TARGET_DEPS += historical-release-notes-835.md
TARGET_DEPS += images-754.md
TARGET_DEPS += installation-755.md
TARGET_DEPS += installation-and-configuration-checklist-750.md
TARGET_DEPS += install-with-lxd-757.md
TARGET_DEPS += intel-rack-scale-design-rsd-introduction-817.md
TARGET_DEPS += interactive-search-819.md
TARGET_DEPS += introduction-to-controllers-786.md
TARGET_DEPS += introduction-to-kvms-808.md
TARGET_DEPS += introduction-to-machines-829.md
TARGET_DEPS += introduction-to-vm-hosting-1524.md
TARGET_DEPS += ip-ranges-760.md
TARGET_DEPS += ipv6-addressing-761.md
TARGET_DEPS += kernel-boot-options-827.md
TARGET_DEPS += kvm-host-networking-807.md
TARGET_DEPS += kvm-host-storage-pools-809.md
TARGET_DEPS += language-details-contributing-to-maas-docs-745.md
TARGET_DEPS += local-image-mirror-752.md
TARGET_DEPS += logging-776.md
TARGET_DEPS += maas-2-6-release-notes-836.md
TARGET_DEPS += maas-cli-802.md
TARGET_DEPS += maas-communication-783.md
TARGET_DEPS += maas-documentation-25.md
TARGET_DEPS += maas-image-builder-1112.md
TARGET_DEPS += maas-installation-from-a-snap-773.md
TARGET_DEPS += maas-installation-from-iso-756.md
TARGET_DEPS += maas-installation-from-packages-769.md
TARGET_DEPS += maas-logging-1468.md
TARGET_DEPS += maas-requirements-789.md
TARGET_DEPS += maas-security-811.md
TARGET_DEPS += maas-tags-834.md
TARGET_DEPS += manage-composable-machines-812.md
TARGET_DEPS += managing-dhcp-759.md
TARGET_DEPS += managing-stp-765.md
TARGET_DEPS += network-discovery-758.md
TARGET_DEPS += networking-768.md
TARGET_DEPS += network-testing-1267.md
TARGET_DEPS += ntp-services-762.md
TARGET_DEPS += package-repositories-814.md
TARGET_DEPS += partitions-770.md
TARGET_DEPS += pods-823.md
TARGET_DEPS += postgresql-ha-hot-standby-803.md
TARGET_DEPS += power-management-830.md
TARGET_DEPS += prometheus-metrics-813.md
TARGET_DEPS += proxy-763.md
TARGET_DEPS += python-api-client-810.md
TARGET_DEPS += rack-controllers-771.md
TARGET_DEPS += README.md
TARGET_DEPS += region-controllers-772.md
TARGET_DEPS += resource-pools-831.md
TARGET_DEPS += rsd-storage-818.md
TARGET_DEPS += select-and-import-images-751.md
TARGET_DEPS += storage-775.md
TARGET_DEPS += subnet-management-766.md
TARGET_DEPS += tips-tricks-and-traps-1506.md
TARGET_DEPS += tmp.md
TARGET_DEPS += troubleshooting-837.md
TARGET_DEPS += ubuntu-kernels-828.md
TARGET_DEPS += upgrade-2-3-to-2-4-from-ubuntu-16-04-777.md
TARGET_DEPS += upgrade-from-1-9-to-2-x-778.md
TARGET_DEPS += upgrading-maas-779.md
TARGET_DEPS += user-accounts-790.md
TARGET_DEPS += vm-host-networking-1526.md
TARGET_DEPS += vm-host-storage-pools-1525.md
TARGET_DEPS += vmware-images-753.md
TARGET_DEPS += vmware-vmfs-datastores-780.md
TARGET_DEPS += whats-new-in-2-6-788.md
TARGET_DEPS += whats-new-in-maas-2-6-1305.md
TARGET_DEPS += whats-new-in-maas-2-7-1306.md
TARGET_DEPS += whats-new-in-maas-2-8-1655.md
TARGET_DEPS += working-with-git-and-github-746.md
TARGET_DEPS += writing-guide-747.md
TARGET_DEPS += zone-examples-784.md


%.html: %.md
	cp templates/vanilla-template.html ./template.html
	xpub convert dc2html -t vanilla $<
	scp $@ stormrider.io:/var/www/html/maas-rad/maas-vanilla
	mv $@ maas-vanilla
	cp templates/ui-only-template.html ./template.html
	xpub convert dc2html -t ui $<
	scp $@ stormrider.io:/var/www/html/maas-rad/maas-rad-ui
	mv $@ maas-rad-ui
	cp templates/cli-only-template.html ./template.html
	xpub convert dc2html -t cli $<
	scp $@ stormrider.io:/var/www/html/maas-rad/maas-rad-cli
	cp $@  maas-rad-cli

finale: $(TARGET_DEPS)
	xpub push github



